### ISSUE TITLE
Allow to configure number of digits in plot titles

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#1163]
Related to #1141.

**Comment by zmjones** [comment]
do you envision this as only an option when faceting?

i don't really think this should be configurable. i think we should pick a decent option (such as 3 significant digits) and let people make their own plot if they don't like what we do.

however, if/when i get around to refactoring all of the plots, i was thinking we could have a number of these type of options which are passed in ...

thoughts?

**Comment by larskotthoff** [comment]
Re refactor: Sounds good. I would make this a general option (as we may have plots with numbers in the title apart from facetting). We could even make this a general mlr option.

**Comment by berndbischl** [comment]
@zmjones 
- i often use "%g" with sprintf, that works very well. 
- forcing people to create their own plot, because they just want a few digits more or less is really unrealistic....

in general: i love the container objects. for various reasons. 
but looking at the code complexity of some of current plots it seems very unlikely that many people will rewrite them. yes, in some cases they could. and this does not mean our system is bad, or that we have to implement every imaginable option to configure the plots. just trying to state an observation.

**Comment by zmjones** [comment]
well i do think that the complexity of the plot functions is misleading. they are complex almost entirely because they can output so many different plots. with a fixed input each plot would probably be 3-5 lines (minus arg checking, just data transformation and the plot).

**Comment by berndbischl** [comment]
> so we are agreed then that we will keep things with hard-coded options until we have made more generic functions that we can pass all this stuff to?

if stuff just "works" at the moment, then yes

**Comment by pat-s** [comment]
The cost-benefit really does not apply here. As we do not yet know how the plots in _mlr3_ will look like, I won't put a label on this one.
