### ISSUE TITLE
residual plots

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1200]
we should have a plot which displays residuals of model, for general prediction objects

it should work at least for regr and binary classif.

here is a blog post about this
https://drsimonj.svbtle.com/visualising-residuals

what do we have:
- partial dependency plots. they should actually already do most what is discussed in the blog post in a much nicer manner. maybe we briefly show this in the tutorial, under a topic residual plots?
- giuseppe's residual based plots. are these connected to mlr now? i guess not? 

what do we want:
- at least a plot y vs yhat is missing
- we could add also a loess smoother to that like here 
  http://sharpsightlabs.com/blog/2016/06/21/data-analysis-machine-learning-example-part2/ and show the histogramm of the residuals

**Comment by florianfendt** [comment]
First I'll implement for prediction objects, then we can extend for bmrs.

**Comment by florianfendt** [comment]
@berndbischl @larskotthoff @zmjones 
I might as well implement the plot function both for prediction objects and bmrs now, since this might safe me a lot of refactoring afterwards. My question though is, should I implement S3 methods for the 2 former types or do we want separate functions like ````plotResiduals```` and ````plotBMRResiduals````.
Thanks.

**Comment by larskotthoff** [comment]
I would use S3 here.
