### ISSUE TITLE
plotThreshVsPerfGGVIS - return value

### ISSUE THREAD

**Issue by xhudik** [mlr-org/mlr#1270]
Return value is: "a ggvis plot object " (based on documentation - see `?plotThreshVsPerfGGVIS`). However, if I do:
```{r}
class(plotThreshVsPerfGGVIS(smt))
[1] "shiny.appobj"
```
Which is not ggvis object. 
Is it a bug? If not, how can I get a normal ggvis object, or how can I draw it in shiny?
I need something like:
```{r}
plotThreshVsPerfGGVIS(smt) %>% bind_shiny("plot","gg6")
```
But currently it doesn't work due to non-ggvis object

thanks!

**Comment by zmjones** [comment]
hey @xhudik. currently the way the function is written all the outputs are shiny apps unless the arguments are such that there is no interactivity required to display everything. the docs are wrong apparently. i'll fix that.

it is unclear to me precisely what you are doing and so if you gave me a bit more information i might be able to help. the internal creation of the shiny app is necessary to display all the information implied by the input arguments. it wouldn't be possible to output a ggvis object which contained all this information. 

if you want to create a custom shiny app i would suggest that you use the generation function and then ignore our plotting functions entirely, and just write your own. there are some minor data transformations done in the plotting functions that you might like, and so another thing you could do is to call the ggplot2 function, and extract the data from the plot object.

**Comment by xhudik** [comment]
thanks zmjones!

Basically, I want to put plotThreshVsPerfGGVIS figure into my Shiny app. From your post, it seems plotThreshVsPerfGGVIS' output is Shiny app itself. 
Is there any way how can I put it into Shiny - I believe there should be some easy solution ....

**Comment by zmjones** [comment]
i think it would be much easier to just use generateThreshVsPerfData and integrate that into your shiny app. that is why we separated them into generation/plot functions. integrating the plot function in i think would maybe be possible, but definitely a pain, and basically useless. if you look at the code there isn't a ton done in the plot function.

**Comment by xhudik** [comment]
i see, the only problem is that generateThreshVsPerfData doesnt provide interactivity which is pity....

**Comment by zmjones** [comment]
That is the point though. I don't think it is possible to do what you are asking in a generic way, so we set it up so that the underlying data generating functions are exposed so that you could integrate them into your own custom applications.

If you look at the code in the ggvis plot function you can see that the actual construction of the plot is relatively simple. Cutting out the relevant code and integrating it into your Shiny app shouldn't be too hard. It isn't possible to separate the interactivity built into the shiny app that we create in MLR in a way that is importable into your Shiny app.
