### ISSUE TITLE
parameters when making custom learner didn't work as expected

### ISSUE THREAD

**Issue by HarlanH** [mlr-org/mlr#1271]
Hi, new to mlr. This might be a documentation issue, or maybe it's a feature request. I'm using the documentation for [Integrating Another Learner](https://mlr-org.github.io/mlr-tutorial/release/html/create_learner/index.html) to create a new model type. I got hung up when I used `makeParamSet`, but when I accessed ... from within `trainLearner.whatever`, it was a null list. It appears that the design of `makeParamSet` is that the defaults are NOT passed through unless you pass something else, which is very confusing to me, as it means that they're not actually defaults! 

I think you had in mind a scenario where there was an existing modeling function with defaults, and this is just capturing those defaults. But in my case, there's no such function, so in order to use the defaults, I have to manually check `getHyperPars` for `x`, and if the value is missing, fall back to `getParamSet(lrn)$pars$x$default`. I can't find a function in either mlr or ParamHelpers that will let me compute the parameters with the defaults from the param set. Is there one that I'm missing? If so, that needs to be highlighted in the docs. If not, I'd suggest implementing something, and regardless, the docs could use an update.

Thanks for the package! It's looking great so far!

**Comment by schiffner** [comment]
Hi,

and welcome to mlr!

* You are correct that currently `makeParamSet` is just for documenting the defaults.
* You can use function `getDefaults` from package ParamHelpers to collect all the defaults in a parameter set.
* At the moment only the parameters in the `par.vals` slot of the Learner are passed through to `trainLearner.whatever` via `...`.
* (But some of us are working on a better system for specifying defaults for learner parameters.)

> I think you had in mind a scenario where there was an existing modeling function with defaults, and this is just capturing those defaults. But in my case, there's no such function...

You are correct that the documentation is tailored for the case that there is already a modeling function. But in order to better be able to help you:
Could you provide some more information or a code example? Why is there no modeling function or what is preventing you from creating one with suitable defaults?

We are working on improving the documentation. When you take a look at the devel version of the tutorial the page about creating learners is already much improved (though more detailed info about parameter defaults is still lacking; apologies for that):
https://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html

**Comment by HarlanH** [comment]
Thanks for the quick response!

Here's what I ended up doing inside of `trainLearner.whatever`, which works:

```
params = list(...)
for (x in getParamSet(lrn)$pars) {
  if (is.null(params[[x$id]]))
      params[[x$id]] <- x$default
}
```

I'm trying to port a proprietary algorithm, which doesn't have a nicely wrappable structure, so there's a lot of logic that ends up going inside of `trainLearner`. It wouldn't make a great deal of sense to add another layer of abstraction right now, and I didn't want to put the defaults in two places. 

Thank you to the link to the new tutorial! Will read it carefully!

Will close this ticket!
