### ISSUE TITLE
expvar outside allowed range

### ISSUE THREAD

**Issue by andreashandel** [mlr-org/mlr#1348]
I'm fitting a linear model like such (sorry, not a fully reproducible example, but I hope it is understandable anyway):

```r
sampling_choice = makeResampleDesc("RepCV", reps = 10, folds  = 5)
resample(mylearner, task = mytask, resampling = sampling_choice, measures = list(rmse,rsq,expvar))
```
I get the following:
```
Result: rmse.test.rmse= 155, rsq.test.mean=-4.26, expvar.test.mean= 4.5
```

This is odd, since according to the documentation, expvar is only allowed to be between 0 and 1. I can somewhat guess what's going on: Not very informative and small data (68 observations, 23 predictors) combined with cross-validation gives me a poorly performing model. However, I'm surprised that rsq is so strongly negative and expvar is not between 0 and 1. Can anyone shed some more light on what might be going on here and how I should interpret the >1 value of expvar?

Thanks!

(Btw, I'm not sure but this might be related to issue #1211 ?)

**Comment by catastrophic-failure** [comment]
Hi, `expvar` above 1 is totally allowed. If you check the formula for `expvar`

```splus
measureEXPVAR = function(truth, response) {
  regss = sum((response - mean(truth))^2L)
  ess = sum((truth - mean(truth))^2L)
  regss / ess
}
```

Anytime `regss` > `ess` `expvar` will exceed 1. That only means the predicted responses are more spread around the true value than the true responses. I'd say `expvar` is better suited to learners where regression to the mean is a concern (i.e. most linear models).

Also, no, this isn't related to #1211, there I'm building warning messages for measures that fail on singularities (`expvar` is one of those, it fails in leave-one-out for example)

--

Now, regarding the documentation, it's odd, really. Perhaps we could discuss it.

--

Also, this might be of interest at StackOverflow, if you could post it as a question there. Or, if you prefer, I could post it instead.

**Comment by alexanderbrenning** [comment]
I'd like to pick up this conversation and add to it as there seem to be some more fundamental issues with this performance measure and the implemented messages and metadata:

## Description

- Metadata on the `expvar` measure says `best = 1` and `worst = 0`, which is incorrect as per the discussion above and the reproducible examples below. Neither are these values the upper and lower bounds, nor is `best = 1` necessarily even a desirable outcome (see examples below).
- `expvar` note says `"Similar to measure rsq (R-squared)."` which is not true. It further says `"Defined as explained_sum_of_squares / total_sum_of_squares."`, which does not match the implemented equation, which is residual_sum_of_squares / total_sum_of_squares.
- If `minimize = FALSE` implies that the measure should be maximized instead, then this will lead to misleading model selection since nonsensical predictions may produce larger values than perfect predictions.
- `expvar` as implemented here is not usually referred to as the explained variance, this term may therefore be misleading; see e.g. Li (2017) in PLOS ONE, <https://doi.org/10.1371/journal.pone.0183250>, for a different definition of variance explained in a predictive setting.

## Reproducible example

```r
library("mlr")
set.seed(123)
N <- 1000
truth <- rnorm(N)

expvar
# shows the note and metadata mentioned above

measureEXPVAR(truth, truth)
# 1, as expected

biased_and_useless <- rep(-1, N)
measureEXPVAR(truth, biased_and_useless) 
# 1.0509, that was easy!

nonsense <- truth * (-1)
measureEXPVAR(truth, nonsense) 
# 1.001059, I'm a genius!

greater_nonsense <- nonsense + rnorm(N)
measureEXPVAR(truth, greater_nonsense) 
# 1.8606 - explaining more variance than present in the data?
```

## Expected outcome

- The `name` attribute should be changed to avoid misunderstandings, perhaps "ratio of unexplained to total variance - not the explained variance"
- The `note` should correctly represent the formula used. I'd strongly encourage to include a strong warning that this should not be used as a performance measure, although it should probably not be removed from the code for backward compatibility.
- I'm not sure what to recommend for `best`, `worst`, and `minimize`; is it possible to assign `NA`?

I know `mlr` is not being developed any longer, but since it is still in use, I'd appreciate if this issue could be addressed to avoid confusion or even misguided model selection. Thank you!

**Comment by pat-s** [comment]
@alexanderbrenning 

I've discussed this just right now with @berndbischl and we will remove the measure completely.
There is no benefit in this measure given that it's almost similar to rsq, weakly documented and has a confusing name.
Thanks for reporting!
