### ISSUE TITLE
best practices when default values of parameters depend on each other

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1376]
The new ctree implementation has three parameters that do essentially the same

``` 
makeNumericLearnerParam(id = "alpha", default = 0.05, lower = 0, upper = 1)
makeNumericLearnerParam(id = "mincriterion", default = 1 - alpha, lower = 0, upper = 1)
makeNumericLearnerParam(id = "logmincriterion", default = log(mincriterion), lower = 0, upper = 1)
```

The default values for `mincriterion` and `logmincriterion` given here can not be used in mlr. 
``` 
> classif.lrn = makeLearner("classif.newctree", predict.type = "prob", fix.factors.prediction = TRUE)
 Error in 1 - alpha : non-numeric argument to binary operator 
``` 
What should I do in this case? You can find my current code [here](https://github.com/HeidiSeibold/sandbox/blob/master/rstuff/openml_newctree/new_ctree_mlr.R).

I have tried to find another learner, where paramterers depend on each other and in [`CoxBoost`](https://github.com/mlr-org/mlr/blob/e8801bcb5ad1ac7c5fdfc7b862df7eb4c37a698a/R/RLearner_surv_CoxBoost.R) you have
``` 
CoxBoost(..., subset = 1:length(time), penalty = 9*sum(status[subset]==1), ...)
``` 
but there you do not implement `subset` and have `penalty` as
``` 
makeNumericLearnerParam(id = "penalty", lower = 0)
``` 

So my question is, what are best practices in mlr when default values of parameters depend on each other?

**Comment by larskotthoff** [comment]
Related to #207.

**Comment by jakob-r** [comment]
The link to your current code 404'ed

**Comment by HeidiSeibold** [comment]
Updated the link, thanks :)

**Comment by jakob-r** [comment]
Ok, so I can not give you a definitive answer but some hints:

* with the newest version of ParamHelpers and mlr we support expressions as values for `lower`, `upper` and `default`. But to get the definitve ParamSet you have to call `evaluateParamExpressions(ps, dict = list(...))` and only the items in this dict list will be evaluated in the expressions. So you would have to pass the other parameters that are set. This you can do in the code part of `trainLearner.classif.develpartykit.ctree`.
* Without struggling with what I mentioned before you could directly implement some of the behaviour in the trainLearner part
* Finally, what I would recommend is just to leave the default away and write it in the notes (if, at all) because you can rely on the underlying learner to handle the defaults.
