### ISSUE TITLE
Problem with plotHyperParsEffect

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#1403]
The following minimal example does not work:

```
ps = makeParamSet(makeNumericParam("C", lower = 0.01, upper = 0.1))
gr = makeTuneControlGrid(resolution = 2)
res = tuneParams('regr.ksvm', bh.task, cv2, rmse, ps, gr)
dat = generateHyperParsEffectData(res)
plotHyperParsEffect(dat, x = "C", y = "rmse.test.rmse", plot.type = 'line')

# Error in eval(expr, envir, enclos) : object 'rmse.test.rmse' not found 
```

**Comment by larskotthoff** [comment]
@MasonGallo Removing the `eval` in the pretty names stuff fixes this. Any reason the `eval` is needed (and it's probably not a good idea anyway...)?

**Comment by MasonGallo** [comment]
The `eval` was used to convert the string input into an object so we can pull out the "pretty name". The bug could be fixed by changing the splitting criteria in pretty names or removing eval if there is a better way to convert the string input.

I am starting to wonder if pretty.names is useful API design in general for this context rather than just having the user edit it to what they would like. Maybe it should default to False.

**Comment by larskotthoff** [comment]
Another option would be to remove this argument altogether and tell users in the documentation how they can set this themselves on the returned ggplot object. It would certainly simplify the code a lot.

**Comment by MasonGallo** [comment]
Yes, that's where I was heading. I'm always happy to reduce code complexity. I think there could be a note in the documentation and a reference in the tutorial as a reminder to users. Should be quick I can prob get to this later today or tmw.
