### ISSUE TITLE
pltBMRSummary custom shape

### ISSUE THREAD

**Issue by QuayAu** [mlr-org/mlr#1470]
Hi,
I am interested in changing the shape of the points plotted with plotBMRSummary.
I tried using scale_shape_manual(), which did not have any effect. 

```
library(mlr)
library(ggplot2)
lrns = list(makeLearner("classif.lda"), makeLearner("classif.rpart"))
rdesc = makeResampleDesc("Holdout")
bmr = benchmark(lrns, sonar.task, rdesc)
plt = plotBMRSummary(bmr)
plt + scale_shape_manual(values = c(1, 2))

```

**Comment by jakob-r** [comment]
Hi,
the problem is, that we did not defined any variable to be the aesthetic for the shape so you don't affect something with `scale_shape_manual()` because the scale_shape is simply not present.
However there is a small hack that could help you in simple cases:

```r
plt$layers[[1]]$aes_params$shape = c(17, 15)
```

Another solution would be to write your own `plotBMRSummary2` function that you can simply modify, which should not be so hard.

Alternatively @everyone: Should we just change the line to
```r
p = ggplot(df, aes_string(x = meas.name, y = "task.id", col = "learner.id", shape = "learner.id"))
```
for plotBMRSummary() ?

**Comment by berndbischl** [comment]
@QuayAu will likely add a fix here soon
