### ISSUE TITLE
plotBMRBoxplots fails when the same learner is used multiple times (with different ids)

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1523]
```
lrns = list(
  rf = makeLearner("classif.randomForest", id = "rf1"),
  rf2 = makeLearner("classif.randomForest", id = "rf2")
)


bm = benchmark(lrns, iris.task, hout)

plotBMRBoxplots(bm)
```

![bug](https://cloud.githubusercontent.com/assets/7561944/22991656/5298c3a8-f3bd-11e6-8ce6-ef8b3955714b.png)

This is because the `shortname` is the same for both learners, when I set `pretty.names=FALSE` it works

**Comment by larskotthoff** [comment]
Is this actually a bug? I.e. do we want to detect such things and adjust the options accordingly? Or output a warning?

**Comment by berndbischl** [comment]
> Is this actually a bug? I.e. do we want to detect such things and adjust the options accordingly? Or output a warning?

we want to output an error when the shortnames are not unique (and prettynames is on)
the resulting plot is otherwise extremely confusing.

and we want a better setter for names. like
setLearnerNames(id, short.name, name) i would suggest.

we can separate issues for this. not that for the plot functions we might have to check multiple functions for the same problem
