### ISSUE TITLE
createDummyFeatures doesn't work for numeric variables

### ISSUE THREAD

**Issue by terzieff** [mlr-org/mlr#1534]
In https://github.com/mlr-org/mlr/pull/1391 it's been said that 
> createDummyFeatures works now for vectors (numerics and characters)

but AFAICS it really doesn't work for numerics.

```
df1 <- data.frame(id = 1:4, year = as.numeric(1991:1994))
createDummyFeatures(df1, cols = 'year')
 ```
results in
```
 Error in createDummyFeatures(df1, cols = "year") : 
  Assertion on 'choices' failed. Must be of length >= 1, but has length 0. 
```

whereas I'd expect something like
```
dummies::dummy.data.frame(df1, 'year')

  id year1991 year1992 year1993 year1994
1  1        1        0        0        0
2  2        0        1        0        0
3  3        0        0        1        0
4  4        0        0        0        1
```

It it possible to make `createDummyFeatures` work not only for character/factor variables?

PS Another example from the [dummies](https://github.com/decisionpatterns/r-dummies) pkg:
```
foo <- 1:4
dummies::dummy(foo)

     foo1 foo2 foo3 foo4
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

**Comment by ja-thomas** [comment]
I see your usecase, which could be easily solved by converting `'year'` in a factor.

We could discuss if we want to allow the user to generate dummy features from numeric variables.

pro: The are certainly use-cases where you want to do this.

con: This may be error prone, as you normally don't dummy code "real" numeric values.


We can throw a warning/message if we convert it, but I still don't really like that. I would suggest we keep it as it is because users can still convert by hand

**Comment by jakob-r** [comment]
I think having the user to convert a numeric to a factor before creating the task is absolutely okay. Changing the scale of a variable is a "mistake" I would like to leave to the user.
