### ISSUE TITLE
extractFDAFeatures API

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1548]
ok, one problem is that we would like to have that function "act" on a task.

but we also need a basic "workhorse". for this we need to act on data (and target, do we really need the target for anything?).

so the current API is good, but we need to document that one line in "data" is always one complete time series.

**Comment by berndbischl** [comment]
and really learn from the design in Impute.R and ImputeMethods.R to see how to delegate to specific algorithms, and how "reimpute" works during prediction time.

**Comment by pfistfl** [comment]
So, I worked on this on since friday: 

It is mostly done similar to impute.R and imputeMethods.R

Current API: 
```
  t = extractFDAFeatures(fuelSubset.task, 
     feat.methods = list("UVVIS" = extractFDAMean(),
                                    "NIR" = extractFDAFourier(trafo.coeff = "amplitude")))
```
It should return a `Task`, but I have not solved that yet. 

It currently returns a list, where
- $data is a  **data.frame** containing the transformed values for each functional feature
- $desc is a **extractFDAFeatDesc** containing a description Object for extraction in predict phase.

`extractFDAFeatures` can be called for a `data.frame` as well, then `target`,  `fd.features` and `fd.grids`, usually contained in the `TaskDesc`have to be supplied as well.


For predict phase we can pass a **Task** and a **extractFDAFeatDesc**
```
  t2 = reExtractFDAFeatures(fuelSubset.task, t$desc)
```


Questions: 

- Discuss function and object names!

- For `extractFDAFeatures.Task` and `reExtractFDAFeatures.Task` we want to return a Task.
  This can either be done by changing the data of the old task and removing the FDATask class
  or by constructing a new Task and passing on the neccessary `TaskDesc` values.

- What else needs to be changed, so resampling automatically works? 

- We might want some way of appending extracted Features to a Task, for example if i want 
`min, max, mean` or Fourier `amplitude`and `phase` I would have to somehow do it once for each Method and then changeData? 

- Do we need a `convertFDATaskToNormalTask`? 
  We could do this by simply wrapping around ``extractFDAFeatures.Task`` or do we want to rename the 
  function?
