### ISSUE TITLE
classif.C50 learner objects always differ

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1573]
Tow C50 learner objects are not equal:

```r
lrn1 = makeLearner("classif.C50")
lrn2 = makeLearner("classif.C50")
all.equal(lrn1, lrn2)
# [1] "Component “par.set”: Component “pars”: Component “seed”: Component “default”: Mean relative difference: 0.3536315"
```

The problem is the seed parameter in the param set which is stochastic:
https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_C50.R#L21

```
getDefaults(getParamSet(lrn1))$seed
# [1] 3153
getDefaults(getParamSet(lrn2))$seed
# [1] 2038
```

Do we want this behaviour? An alternative would be to set the "stochastic" seed in the `trainLearner` function and not when creating the learner object.

If we keep this behaviour, I need to change something in OpenML otherwise C50 learners are always recognized as a new flow (we always upload learner objects on OpenML).

**Comment by mb706** [comment]
If you take out the seed from the paramset defaults, you don't need to set it in `trainLearner`, since `sample.int(...)` is literally the default of the seed parameter in `C5.0Control`.

Also, imho, you should not set the seed in the defaults. it doesn't happen for other learner's seeds either (`randomForestSRC`, `ranger`, ...) where the seed, if not given, is also set to some `runif(...)`. (Only in these cases it happens somewhere in the function, not in the function header)

**Comment by mb706** [comment]
Also since we're here, I'd argue `sample` should have `tunable = FALSE`.

**Comment by berndbischl** [comment]
We should not set sample the seed in the paramset. It violates our policy and is weird to do that. We define a default it is normally representable with PH capabilities. If not we leave it out. The latter is the case here.

**Comment by berndbischl** [comment]
And please note that there is really no reason now sample a seed in trainlearner or anywhere else! We want to minimize doing extra stuff in mlr wrappers , not add stuff which has no real effect.

**Comment by berndbischl** [comment]
Sample is tunable. I affects time as well as other perfromance metrics
