### ISSUE TITLE
helpLearner unit test - mini issue

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1745]
hi,

1) the unit test should not produce output like this
```
helpLearner: ..Choose help page:
1 : qda
2 : predict.qda
0 : cancel
...:  
.Choose help page:
1 : qda
2 : predict.qda
0 : cancel
...:  
Choose help page:
1 : qda
2 : predict.qda
0 : cancel
...:  
1Choose help page:
1 : qda
2 : predict.qda
0 : cancel
...:  
...No information about learner classif.qda.bagged found.
........The following parameters are missing documentation:
  alpha
....Documentation for the following parameters is present:
- method (MASS::qda)
- nu (MASS::qda)
The following parameters are missing documentation:
  predict.method
.Documentation for the following parameters is present:
- method (MASS::qda)
- nu (MASS::qda)
The following parameters are missing documentation:
  predict.method
.
```

2) i also worry that the interactive requests to select a page look a bit strange. can that potentially block the tests?

**Comment by berndbischl** [comment]
the best way to handle 1) could be to muffle with expect_output

**Comment by berndbischl** [comment]
i also get a local failure?

Failed -------------------------------------------------------------------------
1. Failure: helpLearner of learner with multiple help pages (@test_base_learnerHelp.R#25) 
utils::help("regr.randomForest", package = "mlr") not equivalent to testfn("regr.randomForest").
Lengths (0, 1) differ (string compare on first 0)

**Comment by mb706** [comment]
The local fail might be because devtools breaks help in some way? When I `devtools::load_all` mlr and do
```R
> str(utils::help("regr.randomForest", package="mlr"))
Class 'help_files_with_topic'  atomic (0)
```
it is an `atomic (0)` (with some attributes), while for some normal package, e.g.
```R
> str(utils::help("lm"))
Class 'help_files_with_topic'  atomic [1:1] /usr/lib64/R/library/stats/help/lm
```
is the location of the help file. So far, I assumed that this happens because I have the github version of devtools on my machine (a plain `help("regr.randomForest")` gives me an error after `load_all`) and wasn't really bothered because of that.

The test does not fail when doing `CMD check` (and obviously works on Travis).

I am at a loss here as to how to handle this: The test is *about* checking whether `helpLearner` returns a help page. `devtools` breaks getting help pages. Is this a fail?

**Comment by mb706** [comment]
Re: interactive requests blocking tests: I don't think it is at fault for breaking the Travis test (since that appears to have happened randomly), but now I made sure that `readline` never gets called during the tests even if e.g. the length of `callees` for `classif.logreg` ever changes.

**Comment by berndbischl** [comment]
well, i dont know.

the point is that i need to be able to run rtest --filter=base (well or rtest with any filter) without errors.

if you dont know how to handle this, disable the test and create a clean issue. or configure the test so it only runs on travis.

**Comment by mb706** [comment]
Current #1748 should fix this. Can you check?
