### ISSUE TITLE
measures: bac and ber inconsistent?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1834]
why does bac not allow multiclass?

**Comment by AlexEngelhardt** [comment]
`ber` is implemented as `mean(diag(1 - (table(truth, response)/table(truth, truth))))`, while `bac` is based on the `measureTP` and `measureTN`.

```
> measureBAC
function (truth, response, negative, positive) 
{
    mean(c(measureTP(truth, response, positive)/sum(truth == 
        positive), measureTN(truth, response, negative)/sum(truth == 
        negative)))
}
```

These two (TP and TN) are not implemented for multiclass. I think you would have one true positive rate *per class*, no? Alternatively, you'd have to specify the "positive" class beforehand.

I'm not sure which way is the best here, but if you clarify this, I can take a stab at the issue.

**Comment by giuseppec** [comment]
The issue here seems to be that ber is defined in terms of the confusionmatrix while bac is defined using measureTP and measureTN. 

I guess this issue can be fixed by defining `measureBAC = 1 - measureBER`  and onpening a new issue that explains why `measureTP and measureTN` do not work for multiclass with some concrete examples and unit tests (e.g. to check if several "special cases" work, i.e. when TP or TN is 0).

I always have to check this page for that kind of measures https://en.wikipedia.org/wiki/Evaluation_of_binary_classifiers
