### ISSUE TITLE
Use makePreprocWrapper for NLP preprocessing ?

### ISSUE THREAD

**Issue by behrica** [mlr-org/mlr#1853]
I am rather new to mlr, but like it already a lot .
So I have a question in the natural language processing area.

I want to use mlr for classifying text.

In this the "data preparation", so how to go from "input text" to a "feature matrix" has typically lots of options, which I would like to idealy "tune" in the "tuning framework" of mlr.
(So going from a single "feature" (the text) to "multiple features")

On example might be a parameter which sets the "size of the bag of words",
other could be "should stemming be done ?'.

I though that it might be feasable to do this using the "makrePreprocWrapper" function.

Is this possible and has somebody tried this and can give me an example ?

Or is it better to do this "tuning" complety outside of mlr ?

**Comment by andrewjohnlowe** [comment]
I tried to do something similar a couple of months ago but was not successful. I would also be grateful for an answer to this!

**Comment by jakob-r** [comment]
It a fair bit of more coding, as the preprocessing wrapper works only if the learner could be applied to the task without the preprocessing wrapper - roughly speaking. This is because you have to also supply the wrapped learner with a task which already has to pass some feasibility checks (column checks ans so on) and the wrapped learner also inherits the abilities of the underlying learner and does not extend it out of the box.

With getting deeper into mlr it would be possible but still hard. Do you have multiple texts? How do you validate? This all has to be implemented for text tasks if you want to tune.

**Comment by mb706** [comment]
I think mlr should be suited for this kind of task, especially because of the hyperparameter tuning framework it provides.

There might be some difficulties with the fact that `mlr` really doesn't like `character` typed features. If you create a `Task` object and give it a `data.frame` with `character` features, you will probably have to use `makeClassifTask(......, check.data = FALSE)`. In your PreprocWrapper, you should then try to return data that is numeric / factorial.

Some possible pitfalls are:
* PreprocWrapper assumes that for each line of input data, you create one line of preprocessed data, so you can't split up one row of input into multiple data points, or drop data points. (If you need to do that, you could try something like [writing your own learner](https://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html) that kind of wraps around the mlr learner, but it is probably something you should to outside of mlr)
* You should not modify the target column during preprocessing, even the target column name.

**Comment by behrica** [comment]
It can definitely be done.
I do not need it any more, but I can leave here the code.
It's not fully working, but proves the concept:

It makes an NLP wrapper, which converts a single column of type character 8which would be text) in a bag-of-word representations.

It has a tuning parameters, which decided if the bag-of-word number is either (n (number of occurences), tf-idf, or prsent/not present)

The tricky part is indeed that eventually for training and prediction the dictionary of all used words
could be different. (which would result in different columns/features for both cases)
So I need to pass the full dictionary between the training and prediction functions and merge 
the featurs with 0-features of all non-existing words in traininig.

This might even be not enough, dependening on sample strategy.
So it needed a global dictionary of all used words or similar.


```
clean_names <- function(dat) {
    old_names <- names(dat)
    new_names <- old_names %>% 
        gsub("'", "", .) %>% 
        gsub("\"","", .) %>% 
        gsub("%", "percent", .) %>% 
        gsub("^[ ]+", "", .) %>% 
        make.names(.) %>% 
        gsub("[.]+", "_", .) %>% 
        gsub("[_]+", "_", .) %>% 
        tolower(.) %>% 
        gsub("_$", "", .) %>%
        ## here is the new line to transliterate the characters ##
        stringi::stri_trans_general("latin-ascii") 
    
    dupe_count <- sapply(1:length(new_names), function(i) {
        sum(new_names[i] == new_names[1:i])
    })
    new_names[dupe_count > 1] <- paste(new_names[dupe_count > 1], dupe_count[dupe_count > 1], sep = "_")
    stats::setNames(dat, new_names)
}



makeFeatures <- function(data,countType) {
    if (countType=="present") {
        present=T
        countColumn = "n"
    } else {
        countColumn=countType
        present=F
    }
    

    srs.words <- data %>%
        unnest_tokens(word,text) %>%
        anti_join(stop_words,by="word") %>%
        filter(str_count(word)>2,
               !grepl("\\d",word)
               ) %>%
        mutate(word=wordStem(word,language = "english")) %>%
        filter(!grepl("[^\u0001-\u007F]+", word))


    rareWords <-
        srs.words %>%
        count(word) %>%
        filter(n<100)
    
    counts  <- srs.words %>%
        anti_join(rareWords,by="word") %>%
        count(refid,word) %>%
        ungroup() %>%
        bind_tf_idf(word, refid, n) %>%
        select(refid,word,countColumn) 

    if (present) {
        counts <- counts %>%
            mutate(n=ifelse(n>0,1,0))
        
     }

    
    features <- counts %>%
        spread_("word",countColumn,fill=0) %>%
        clean_names()

        

    features
    
}


trainFunction <- function(data,target,args) {
    vars = setdiff(colnames(data), target)  
    features = makeFeatures(data[vars],args$countType) 
    missingWords<-setdiff(allWords,colnames(features))
    null_df <- matrix(c(0),nrow=nrow(features),ncol=length(missingWords)) %>%
        magrittr::set_colnames(missingWords) %>%
        tbl_df()
    allData <- bind_cols(features,null_df) %>%
        data.frame()
    allData$primary_research=data$primary_research
    control = list()
    return(list(data = allData, control = control))
}


predictFunction <- function(data, target, args, control) {
    features = makeFeatures(data,args$countType) 
    missingWords<-setdiff(allWords,colnames(features))
    null_df <- matrix(c(0),nrow=nrow(features),ncol=length(missingWords)) %>%
        magrittr::set_colnames(missingWords) %>%
        tbl_df()

    allData <- bind_cols(features,null_df) %>%
        data.frame()
    return(allData)
    
    
}


wrapper=makePreprocWrapper("classif.randomForestSRC",trainFunction,predictFunction,
                           makeParamSet(
                               makeDiscreteParam("countType",values=c("n","tf_idf","present"))))
