### ISSUE TITLE
extract (new)data from class prediction

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1855]
Background: for the Area under the Mass Volume Curve with resampling (a measure for unsupervised learning), I need to subsample the features of the train and test data in several iterations in order to evaluate the model.
(Paper: How to Evaluate the quality of Unsupervised Anomaly Detection Algorithms? Nicolas Goix)

I need to access the data in my prediction object. But there are several ways how the data for prediction is created:
1. have test and train data in the task and use the input variable subset in the train and predict fct
2. have only train data in the task and predict only the train data
3. have only train data in the task and input `newdata` in the predict fct

I don't see a easy way how to access the train data and predict data, without making a lot of checks for case 1 and 2. And in case 3 there is no way to access the newdata from the prediction object.

- Best case for me would be accessing the train and predict data directly from the train and predict object, but this would change the current structure of mlr.
- An alternative is to oblige the user to use case 1. But there are no predefined properties like `req.subset` for the performance measures, yet.

Any other ideas are very welcome?

**Comment by mb706** [comment]
So how does this evaluation work? You train the model, then iteratively compute the test data's empirical MV for random subspaces, or you iteratively train the model *on random subspaces of the training data* and then compute the test data empirical MV for the same random subspaces? (Or am I completely off?)

In the first case, it would AFAICS not be necessary for the evaluation to have the training data.

**Comment by MinhAnhL** [comment]
The second case. You train the model on random selected features of the training data and than compute the MV or AMV on test data with the same sampled features, as far as I understood the paper.
For computing the ||MV_hat{s}_k|| or AMV see also paper: Learning Hyperparameters for Unsupervised Anomaly Detection from Albert Thomas.

**Comment by mb706** [comment]
I think some of the difficulty here is that you would essentially be training multiple models, and the `Prediction` object is not fit to handle that well.

If you were to forget Goix for a moment and do this evaluation with the full feature set only, I think you would do well if your model had a `predict.type` "superlevel.size" (or whatever, what Goix calls Leb(*s* &ge; *u*) for the score of each data point *u*(*X*)), the model calculated that value, and your measure could then empirically estimate MV from that. It would be relatively straightforward to write some kind of "superlevel.size"-calculating wrapper that does the MC calculation for that. (The feasibility of this might depend on what method you use to calculate Leb()? I don't really understand why Thomas discretizes in his Alg 1, but if he has a good reason this might not work so well.)
(Alternatively you could also have the model return just the score and do the MC calculation in your measure / evaluation, but the benefit of having the model do it is that it would be possible to do it only once, during training, not every time a prediction is evaluated.)
Your measure could then estimate MV from this alone (and, if needed, the outlier truth info), since Leb(*u*) is monotonic in *u* and therefore you have the empirical **P**(*s* &ge; *u*).

To do Goix, you could to do something almost kind of like feature bagging, except that you want the predictions not averaged over the models, but you want the predictions of each trained model individually. It would probably be quite possible to modify the `BaggingWrapper` to do that. Your prediction should then contain the columns `turth, leb.1, leb.2, leb.3, ...`, with `leb` calculated for each random feature subset. Your measure could then just calculate the AMV for each column and then average to get the end result.

At least that's my thoughts; sorry if I'm telling you stuff thats well known to you and doesn't work because of \*obvious thing I overlooked\*.
