### ISSUE TITLE
Keras/TensorFlow learners

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#1864]
Do you have any plans to implement TensorFlow learners now that that there's good access to the TensorFlow API with R?

https://tensorflow.rstudio.com/
https://github.com/rstudio/tensorflow
https://cran.r-project.org/web/packages/tensorflow/index.html

Thanks!

**Comment by enricoferrero** [comment]
Now that there is a R interface to keras, perhaps a better way to do this would be to wrap keras models directly?

https://rstudio.github.io/keras/
https://github.com/rstudio/keras

CC @topepo @jjallaire

**Comment by larskotthoff** [comment]
We don't have concrete plans to do this at the moment, but if you want to make a pull request we'd be happy to help!

**Comment by berndbischl** [comment]
@bklppr @NiklasDL 
do you guys want to take a look at this?

**Comment by ja-thomas** [comment]
Just my 5ct. 

We (that means @bklppr mostly) are currently implementing mxnet in a very flexible form as a DL framework to mlr (see #1837 ). It is not totally trivial to implement the sequential structure of DNNs in our parameter set framework. 

Adding further DL frameworks is, imo, rather lower priority, especially since they are very similar in what they can do. If there are any good reasons to support Keras instead/additionally feel free to tell us. 

Alternatively, if there is a simple interface, (similar to `mx.mlp`) we can easily support that, but don't have the full flexibility of the framework,

**Comment by berndbischl** [comment]
this is ok for me. i would possibly imagine that some people have some specific constraints on what frameworks they would like to use. 

still agree with what you said.

will close until someone starts working on this

**Comment by susanne-207** [comment]
@pfistfl implemented some extra learners for mlr including keras. You can find it [here](https://github.com/pfistfl/mlr-extralearner/tree/master/R).

**Comment by pat-s** [comment]
@pfistfl Can you put those directly into `mlr-extralearners`?
