### ISSUE TITLE
Add Quantile Regression option

### ISSUE THREAD

**Issue by ktcorby** [mlr-org/mlr#1874]
I would like to see support for quantile regression in mlr. 

I have added a first cut in this branch:
https://github.com/ktcorby/mlr/tree/quantile_regression

This includes two new base learners: qr from the quantreg package and quantregForest from the quantregForest package. It also includes an option to specify the predict.type = "quantiles" for regression models that have the "quantiles" property. I have tested this with train and predict and it seems to work OK. 

Also, I edited the stacked learner code so that base learners can predict quantiles and the super learner will use all of the quantiles as features. This only works for the stack.cv and stack.nocv options right now. 

I would appreciate feedback on the possibility of getting this merged into mlr. I'm sure my branch needs work but it's good enough for my use right now and I don't want to spend time polishing it unless there is a good chance of getting it merged into master.

By the way mlr is great, thank you.

- Kevin

**Comment by catastrophic-failure** [comment]
I had touched this on issue #1022

As I'm a bit away from `mlr` I'm not sure where the efforts are concentrated right now, but you can count me in to help when I have the time. And while I'm not a member you can be assured this is of interest, others have mentioned it before (last time I looked `mboost` was lacking some families due to that, for example, see the discussion in #662).

So, basically, first you need to know what (if any) API changes are necessary to have it working, and how will quantile regression fit within the rest of the learning tasks (this depends on the team members as well).
