### ISSUE TITLE
Problem in feature/observation sampling in BaggingWrapper 

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1879]
In `trainLearner.BaggingWrapper()` `bw.iter` models are generated, each model should have a random subsample of observation and a random subsample of features.
But it seems like every generated submodel has the same observation and feature subsample.

An Example:
set a breakpoint in line 102 in `trainLearner.BaggingWrapper()` in file _BaggingWrapper.R_
here:
> (models = parallelMap(doBaggingTrainIteration, i = seq_len(bw.iters), more.args = args, level = "mlr.ensemble"))

Than run the example from the tutorial Homepage:
> lrn = makeLearner("classif.rpart")
> bag.lrn = makeBaggingWrapper(lrn, bw.iters = 5, bw.replace = TRUE, bw.size = 0.8, bw.feats = 3/4)
> mod.bag = train(bag.lrn, sonar.task) 

Here you should jump to the breakpoint and have a look for i = 1:5 at:

> models[[i]]$features
> models[[i]]$subset

every iteration seems to have the same feature/observation subsample.

That is not on purpose, right?

**Comment by mb706** [comment]
When I do this and then inspect the resulting model, I get:
```R
> lrn = makeLearner("classif.rpart")
> bag.lrn = makeBaggingWrapper(lrn, bw.iters = 5, bw.replace = TRUE,
+   bw.size = 0.8, bw.feats = 3/4)
> mod.bag = train(bag.lrn, sonar.task)
> head(mod.bag$learner.model$next.model[[1]]$features)
[1] "V56" "V53" "V30" "V2"  "V12" "V18"
> head(mod.bag$learner.model$next.model[[2]]$features)
[1] "V60" "V53" "V1"  "V24" "V37" "V54"
> head(mod.bag$learner.model$next.model[[3]]$features)
[1] "V4"  "V10" "V2"  "V55" "V56" "V18"
```
Which looks ok to me.

Maybe it depends on the `parallelMap` mode?

**Comment by MinhAnhL** [comment]
hm, so I asked Laura to run this issue on her computer and she has the same problem.
How do I need to set `parallelMap` then?

**Comment by MinhAnhL** [comment]
ok, I just set 

> parallelStartSocket(2)

and it worked :)
Thank you

**Comment by giuseppec** [comment]
Wait. If you don't set `parallelStartSocket(2)` it always produces the same feature and observation subset? Or when did this happen?

**Comment by MinhAnhL** [comment]
It happens when I don't load `parallelMap`.
I didn't realize the error, as I didn't get a warning.

**Comment by mb706** [comment]
I assumed  you (MinhAnhL) had a weird `parallelMap` setting since this doesn't give any bad behaviour on my machine with standard (uninitialized) `parallelMap`. If it gives bad results for you *even with* uninitialized `parallelMap` this should probably be investigated.

When you execute the commands you give above, but without the break point, and then inspect `mod.bag$learner.model$next.model`, does it still have the same feature / observation subsample? Just to make sure this is not a quirk in the debugger.

**Comment by giuseppec** [comment]
I know what's happening. @MinhAnhL is doing this:

```r
library(devtools)
load_all()
lrn = makeLearner("classif.rpart")
bag.lrn = makeBaggingWrapper(lrn, bw.iters = 5, bw.replace = TRUE, bw.size = 0.8, bw.feats = 3/4)
mod.bag = train(bag.lrn, sonar.task)
head(mod.bag$learner.model$next.model[[1]]$features)
# [1] "V45" "V14" "V24" "V16" "V36" "V11"
head(mod.bag$learner.model$next.model[[2]]$features)
# [1] "V45" "V14" "V24" "V16" "V36" "V11"
```

This is because `load_all()`  sources the `helper_zzz.R` and the line `options(mlr.debug.seed = 123L)` causes this "bug". @mb706 try this:

```r
library(mlr)
options(mlr.debug.seed = 123L)
lrn = makeLearner("classif.rpart")
bag.lrn = makeBaggingWrapper(lrn, bw.iters = 5, bw.replace = TRUE, bw.size = 0.8, bw.feats = 3/4)
mod.bag = train(bag.lrn, sonar.task)
head(mod.bag$learner.model$next.model[[1]]$features)
# [1] "V45" "V14" "V24" "V16" "V36" "V11"
head(mod.bag$learner.model$next.model[[2]]$features)
# [1] "V45" "V14" "V24" "V16" "V36" "V11"
```

You should also get the same feature and observation subsets. Not sure if this is a bug or an expected behaviour of `mlr.debug.seed`.

**Comment by mb706** [comment]
Well spotted. The problem is that `train` sets the seed  when called as `train(bag.lrn, sonar.task)`, but resets it in the `train` call inside `doBaggingTrainIteration`. This is also the reason why there is no such problem when using `parallelMap` processes: the seed reset happens at the *end* of  `doBaggingTrainIteration`.

IMHO this is a bug. The solution would be to create the column and row subsets inside `trainLearner.BaggingWrapper` all at once, and then hand them to the `doBaggingTrainIteration` call.
