### ISSUE TITLE
MMCE output but no features

### ISSUE THREAD

**Issue by albert3858** [mlr-org/mlr#1997]
Not sure if this is a bug or expected behaviour under certain circumstances. I am following the guide here for feature selection using wrapper methods:
https://mlr-org.github.io/mlr-tutorial/devel/html/nested_resampling/index.html#tuning

Occasionally the search outputs a valid MMCE using the code below, but without any corresponding features. The if clause catches it and inserts a placeholder value so execution can complete. It seems to happen perhaps once or twice in every 50-60 iterations. Is there any reason/situation where this could happen by intent? If not I'll post more info plus example. Many thanks.

```featscores[j, 1] <<- which.min(r$measures.test[[2]])
  featscores[j, 2] <<-  min(r$measures.test[[2]])
  cat(featscores[j, 1], "\n")
  cat(featscores[j, 2], "\n")
  
  if (length(r$extract[[which.min(r$measures.test[[2]])]]$x) == 0) {
    cat("PROBLEM HERE!")
    fts <<- "V0"
  } else{
    fts <<- r$extract[[which.min(r$measures.test[[2]])]]$x
    
  }
```

**Comment by albert3858** [comment]
Further output below. As can be seen, only some iterations are failing to return features. However, both iterations 2 and 3 did return valid $y values.

Browse[2]> r$extract[[1]]$x
[1] "V1"
Browse[2]> r$extract[[2]]$x
[1] "V8"
Browse[2]> r$extract[[3]]$x
character(0)
Browse[2]> r$extract[[4]]$x
character(0)
Browse[2]> r$extract[[5]]$x
[1] "V3" "V7"
Browse[2]> r$extract[[6]]$x
[1] "V10"
Browse[2]> r$extract[[7]]$x
[1] "V3" "V7"
Browse[2]> r$extract[[8]]$x
[1] "V13"
Browse[2]> r$extract[[9]]$x
[1] "V5"
Browse[2]> r$extract[[10]]$x
[1] "V3"

**Comment by jakob-r** [comment]
Can you show how you construct the learner and how exactly do you wrap it?

**Comment by berndbischl** [comment]
@albert3858 it is really hard to understand the problem here. 
pls post some reproducible example so we have a chance to help.

PS:
If I understand your question correctly: Are you are asking why sometimes the char(0) vector is returned?
Thats "expected" behavior, or at least valid behavior. The empty feature set is still a feature set. 
mlr then produces a featureless "dummy" learner that still predicts labels (without using any features).

That can happen, depending on the info you have in your data set and the setting of the search algorithm (which be both do not know here in your case)

**Comment by albert3858** [comment]
Apologies - have been away for a while - many thanks. That explains it.
