### ISSUE TITLE
cindex calculation

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#2017]
Why is the y multiplicated by -1 when putting it into the rcorr.cens function?

```
cindex = makeMeasure(id = "cindex", minimize = FALSE, best = 1, worst = 0,
  properties = c("surv", "req.pred", "req.truth"),
  name = "Harrell's Concordance index",
  note = "Fraction of all pairs of subjects whose predicted survival times are correctly ordered among all subjects that can actually be ordered. In other words, it is the probability of concordance between the predicted and the observed survival.",
  fun = function(task, model, pred, feats, extra.args) {
    requirePackages("_Hmisc")
    y = getPredictionResponse(pred)
    if (anyMissing(y))
      return(NA_real_)
    s = getPredictionTruth(pred)
    Hmisc::rcorr.cens(-1 * y, s)[["C Index"]]
  }
)
```

**Comment by mllg** [comment]
After some quick testing: Seems to be a bug. :disappointed:

**Comment by berndbischl** [comment]
pls fix ASAP (with unit test). thats bad

**Comment by berndbischl** [comment]
if measures are introduced, pls ALWAYS unit test them a lot and properly

@larskotthoff

**Comment by PhilippPro** [comment]
I think it is not wrong. At least when we compare to cindex.uno, we obtain similar values with the `-1`. I was just wondering why it is done.

**Comment by berndbischl** [comment]
at least comment the code then. and really check whether we have enough proper unit tests

**Comment by PhilippPro** [comment]
But when I use ranger in the code, my cindex is still 0.97, and the plot shows the same negative correlation. I looked into the ranger code and we take the mean of the cumulative hazard `rowMeans(p$chf)` as prediction for survival time. Is this reasonable?

**Comment by AlexEngelhardt** [comment]
The [surv.ranger tests](https://github.com/mlr-org/mlr/blob/bb32eb8f6e7cbcd3a653440325a28632843de9f6/tests/testthat/test_surv_ranger.R) don't exist yet, so a bug here is possible in principle.

[This commit](https://github.com/mlr-org/mlr/commit/9d57cc4711b2474963b5597f4e6c9e36506a7ccd) changed the returned object from p$survival (the estimated survival function) to p$chf (the estimated cumulative hazard function).

And here I'm stuck. I don't know why p$chf returns an n*n matrix, and what the row / column entries represent. The ranger help just says these are the "estimated cumulative hazard function", but why is it n*n?

Sorry, I can't be of more help here I think :/

**Comment by PhilippPro** [comment]
I think p$chf is quite clear, the estimated hazard function. It has as many rows as observations and as many columns as different time points. I still do not get, why the mean of this function should be the expected time.

**Comment by pat-s** [comment]
Uff, reads somewhat complicated.

@AlexEngelhardt @PhilippPro 

Did you do more research on this? What is your view today about this issue? Is it a bug or is it still "complicated"?

**Comment by PhilippPro** [comment]
No idea. I did not work on it.

**Comment by AlexEngelhardt** [comment]
Same here. It turned out way harder than anticipated.

**Comment by mnwright** [comment]
The CHF is **not** the expected survival time. It is the (predicted) cumulative hazard for each observation and time point. In ranger (and also in rfsrc), we estimate the CHF in the terminal nodes. Afterwards, we calculate the survival function at each time point by
`result$survival <- exp(-result$chf)`

For the C-index, we need a single scalar estimate of risk for each observation and for that we sum the CHF over time (as proposed by [Ishwaran et al.](https://doi.org/10.1214/08-AOAS169)). I think you compute this sum in `predictLearner.surv.ranger()`.

Anyway, `Hmisc::rcorr.cens()` calculates the concordance to true **survival** function so that you have to multiply a **hazard** estimate by `-1` and the current implementation is correct. You might want to check whether every survival learner predicts a measure of hazard or risk and not of survival. It looks good for `surv.ranger`, `surv.randomForestSRC` and `surv.coxph` (models the hazard, so the linear predictor is a measure of hazard). I didn't check the others.

**Comment by pat-s** [comment]
Thanks Marvin! This really helps.
