### ISSUE TITLE
Error message of missing packages appears after a long time of calculation instead before

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2022]
Hello,

my question refers to "generateFilterValuesData". I liked to use this function on a dataset and liked to use methods of "care" or "Rfast" and others. Both packages were not installed. The calculation started and at the end I received an error message that Rfast or Care are not installed.

Wouldn't it be better to check BEFORE starting the calculation whether all packages that are necessary are already there (based on the chosen methods by method=c(....))? And if not -> Error before starting the calculation with the existing methods or calculation continues with the existing one and a warning that not every method exists? 

Best regards
Markus

**Comment by larskotthoff** [comment]
Thanks for the suggestion. mlr uses so many packages that unfortunately it isn't really feasible (from a programming and performance point of view) to check every time before a function from another package is used. If the packages are not installed, the computations should fail quickly though so that you don't lose a lot of time.

**Comment by jakob-r** [comment]
To prevent this you could install mlr with all suggestions `install.packages("mlr", dependencies=TRUE)`
