### ISSUE TITLE
Travis build should regenerate example tasks

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#2109]
See #2107 -- avoid issues like this.

**Comment by mb706** [comment]
Apparently the `makeData.R` doesn't generate the `bc.task.spatial`, but creates the `gunpoint.task` twice.

**Comment by pat-s** [comment]
Is `makeData.R` still in use? Apparently it creates `.RData` files but all files in data are `.rda`.

**Comment by mb706** [comment]
The files are `.rda` since [this](https://github.com/mlr-org/mlr/commit/e865e491dc2062b14ebeb9d5314cec2532c1bc2a) commit, which is a merge of [this](https://github.com/mlr-org/mlr/pull/1891) PR ;-)

**Comment by pat-s** [comment]
I know :smile: I'am just wondering if `makeData.R` is a manual helper script for creating all datasets that should also be updated or is somehow used by travis (apparently not, as otherwise the data files would have again changed to `.RData`). 

I used `devtools::use_data()` when adding `is.spatial` to all datasets. Default it writes `.rda` files (which is the same as `.RData` afaik)

**Comment by larskotthoff** [comment]
Yes, and I don't think we need to be constrained by what format/process generated these files in the past as long as we end up with something better :)
