### ISSUE TITLE
Can not tune parameter "scale_pos_weight" of learner "classif.xgboost"

### ISSUE THREAD

**Issue by jyk** [mlr-org/mlr#2120]
I would like to tune hyperparameter "scale_pos_weight" (see section "Handle Imbalanced Dataset" in https://github.com/dmlc/xgboost/blob/master/doc/how_to/param_tuning.md) in mlr.
I have got error message: "Can only tune parameters for which learner parameters exist: scale_pos_weight
".
I used next parameters for tuning:
    ps <- ParamHelpers::makeParamSet(
      makeIntegerParam(id = "nrounds", lower = 200, upper = 2500, default = 200),
      makeNumericParam(id = "eta", lower = -7, upper = -5, default = -6, trafo = function(x) 2^x),
      makeIntegerParam(id = "max_depth", lower = 3, upper = 15, default = 3),
      makeNumericParam(id = "colsample_bytree", lower = 0.3, upper = 1, default = 0.6),
      makeNumericParam(id = "subsample", lower = 0.3, upper = 1, default = 0.6),
      **makeNumericParam(id = "scale_pos_weight", lower = 1, upper = 100, default = 49.8)**
    )

Why I can not tune hyperparameter "scale_pos_weight" with mlr / mlrMBO ?

**Comment by jyk** [comment]
I tried to set this hyperparameter (scale_pos_weight) by hand but it appeared that mlr does not support this hyperparameter at all:
cl1 = makeLearner("classif.xgboost")
cl2 = setHyperPars(cl1, scale_pos_weight = 10)
I have got: 

Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.xgboost: Setting parameter scale_pos_weight without available description object!
Did you mean one of these hyperparameters instead: min_child_weight silent max_depth
You can switch off this check by using configureMlr!

**Comment by mb706** [comment]
For each of its "Learners" mlr stores its own list of parameters and their domains. Since xgboost seems to add new parameters quite frequently, mlr is a bit out of date here and does not know about the "`scale_pos_weight`" parameter. To get the list of "supported" parameters, call
```R
getParamSet("classif.xgboost")
```
you'll see the `scale_pos_weight` is missing.

I am not aware of any switch that disables the check you're running into (maybe the `on.par.without.desc` should do that?).

You can try to add the parameter you want to use manually:
```R
lrn = makeLearner("classif.xgboost")
lrn$par.set = c(lrn$par.set,
  makeParamSet(
    makeNumericLearnerParam("scale_pos_weight")))
```
and then use this `lrn` for tuning.

**Comment by jyk** [comment]
Thanks, I will try it
