### ISSUE TITLE
Benchmark Experiment using nested resampling. How to access the inner resampling tuning results? [type-question]

### ISSUE THREAD

**Issue by mlearner-jl** [mlr-org/mlr#2138]
I am using Benchmark Experiments on a task. I am using a nested re-sampling strategy (https://mlr-org.github.io/mlr-tutorial/devel/html/nested_resampling/index.html).
 I create a learner using an inner resampling strategy. For example here is a crude one for c50:
```
### C50 ############################################################################################################################
classif_c50 = makeLearner("classif.C50", predict.type="prob")

##The wrappers are presented in reverse order of application
###One-Hot Encoding
classif_c50 = makeDummyFeaturesWrapper(classif_c50, method = "1-of-n")
###Missing Data Imputation
classif_c50 = makeImputeWrapper(classif_c50, classes = list(numeric = imputeConstant(-99999), integer = imputeConstant(-99999), factor = imputeConstant("==Missing==")), dummy.type = "numeric", dummy.classes = c("numeric","integer"))

##### Tuning #####
inner_resamp = makeResampleDesc("CV", iters=3)
ctrl = makeTuneControlRandom(maxit=3L)
hypss = makeParamSet(
  makeIntegerParam("trials", lower = 1, upper = 30)
  ,makeNumericParam("CF", lower = 0, upper = 1)
)
classif_c50 = makeTuneWrapper(classif_c50, resampling = inner_resamp, par.set = hypss, control = ctrl, measures = list(auc, logloss, f1, ber, acc, bac, mmce, timetrain), show.info=TRUE)
### C50 ############################################################################################################################
```

I then create a benchmark experiment with an outer re-sampling strategy as follows (bench_data is my data.frame):
```
valid_holdout = makeFixedHoldoutInstance(train_indices, valid_indices, nrow(bench_data))
outer_resampling = valid_holdout
trainTask = makeClassifTask(id=training_task_name, data=bench_data, target=target_feature, positive=1, fixup.data="warn", check.data=TRUE)
res = benchmark(tasks = trainTask, learners = lrns, resampling = outer_resampling, measures = list(auc, logloss, f1, ber, acc, bac, mmce, timetrain), show.info = TRUE)
```
I cannot find a way using the getBMR<> functions to extract the inner-resampling results? Is there a way to do this that I am missing?

**Comment by mlearner-jl** [comment]
I'd be very interested if anyone has anything for this?

**Comment by py9mrg** [comment]
Bump. I am having the same problem - I think mlr doesn't seem to be respecting the inner loop resampling. In your case, that means there is no inner loop resampling due to the outer loop hold out.

If you look at their example here: [https://mlr.mlr-org.com/articles/tutorial/usecase_regression.html](https://mlr.mlr-org.com/articles/tutorial/usecase_regression.html)

They use 5-fold CV in both inner and outer resampling. When I manually go in and change it so that the inner is 2, and the outer is 3, then use `getBMRTuneResults` to look at the tuning results, I get 3 inner loop results (I believe there should be 6) for each learner. Likewise if I use `getBMRPerformances` I also get 3 results - but different results (the outer loop results). I really don't understand how they can have the same number of results, to me the `getBMRTuneResults` should return inner*outer number of results.

If I swap the process so I should have 3 inner and 2 outer, I now only get 2 of each from the `getBMRXXX` functions.

Even more weirdly - or I'm being even more stupid - the `getBMRPerformances` results do not seem to be the rmse of the `getBMRTuneResults`.
