### ISSUE TITLE
Question concearning 'benchmark'

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2139]
Hello Bernd & Co.,

a question to  benchmark:

`bench <- benchmark(learners=list(wrap.rf, wrap.xgboost), 
                   tasks=regr.task.resampling, 
                   resamplings=outer.rinst, 
                   measures=rmse, 
                   keep.pred=TRUE,
                   models=TRUE)`

warp.rf and wrap.xgboost are two feature selection wrappers. If I would add a second task, what would happen? It wouldn't be necessary that for each method the variable selection would be carried out two times (for each task), but it will be carried out two times, isn't it? I mean, in this case, the feature selection is carried out on the inner task and resampling, this is independent of the outer tasks that may vary.

So I better don't use a wrapper and call first of all selectFeatures for each learner and then add to benchmark the received features for each learner and create learners2 by adding the specified features for each method?

Thank you very much for the infos.

Best regards,
Markus

**Comment by larskotthoff** [comment]
The point of a wrapper approach is that the most important features for the particular learner and task combination will be identified. So yes, it would be done twice if you added another task, but the results might be different for the different runs (even if the two tasks are different subsets of the same underlying task). In order to get the most accurate estimate of performance with the wrapped learner, keep the wrapped learner and don't use `selectFeatures`.

**Comment by jakob-r** [comment]
I am closing this issue as the question was answered by @larskotthoff. If you feel, that something is missing feel free to reopen and/or ask back.
