### ISSUE TITLE
mlr help inconsistencies

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2169]
The github version `mlr` help seems to have some inconsistencies, especially visible when viewed with the rstudio help browser. As an example, the help for `subsetTask` (on linux, click to enlarge):

![help](https://user-images.githubusercontent.com/15801081/36283124-bb1cab6e-12a3-11e8-9217-4e26fbf7aec8.png)

* Some type names in brackets, others in single quotes, others just as links (at the bottom). Really, they should be in `monospace` font and be links if possible.
* Parameter and return type groups not in brackets as they used to be, and as they are in most other mlr-org and related projects(?). This might be because of the markdown-transition, but then again there are brackets in other places rendered just fine on this page.
* The "('character(1)')" in the description of `feature` are all wrong, possibly introduced by some automatic search-and-replace script?
* getTaskFeatureNames should be a link

For comparison, the [rdocumentation.org](https://www.rdocumentation.org/packages/mlr/versions/2.10/topics/subsetTask) version of the help page of some older `mlr` version.

Many other help pages seem to have similar problems, it might be necessary to clean this up a little.

**Comment by jakob-r** [comment]
Could @pat-s look over it?

**Comment by pat-s** [comment]
Sure I''l take a look.

There is no way I could check all man pages during the conversion so please add other man pages with similar issues.
This btw inherits from inconsistency before, I did a regex replacement and had to adjust a lot manually. `roxygen2md` helped only partly because there was a lot "special" formatting in mlr.
So still there seem to be some leftovers (which does not surprise me).

-- 

> getTaskFeatureNames should be a link

Formatting was correct but it appears that one needs to explicticly set the `@md` tag in a `man-roxgen` template whereas this is not needed for normal help files as there the global `markdown = TRUE` roxygen setting from the description applies.

This fixed almost all issues in `subbsetTask()`. The `[character] | [integer] | [logical]` was indeed formatted wrongly but this is a quick fix. Actually I did this conversion before but somehow something was not catched.

**Comment by jakob-r** [comment]
No worries. Indeed the formatting was always a bit inconsistent so I am not surprised. I will just merge and if other things appear they can be fixed in additional PRs.

**Comment by mb706** [comment]
AFAICT the `features` parameter doc still talks about `character(1)` in places, but (1) `features` may have more than one element and (2) it may be a `logical` and an `integer` as well.

**Comment by pat-s** [comment]
Well, thats a content issue of probably more than just this doc file.
I just focused on the syntax conversion and not on fixing the documentation content per se. 

Imo that should go in a new PR and the title of this issue should be adjusted.

**Comment by mb706** [comment]
Im on mobile so cant really check, but was this error not introduced in the same PR?
