### ISSUE TITLE
Integration of formulas into tasks

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr#2177]
I would like to start the discussion again about the integration of formulas into MLR. I am working on the implementation of `mgcv::gam` and `MASS::glmmPQL` into MLR. It is not possible to integrate them without formulas. 

I discussed this issue with @pat-s and @giuseppec, who already proposed solutions in #1763 and #1899 (Further information in #1740). 

To sum up the drawbacks of both PR:

1. Integration of the formula into the learner
```r 
classif.lrn = makeLearner("classif.gam", formula = "target ~ s(p1) + s(p2)"
```
   - A benchmark with one or multiple learners and multiple tasks would fail because the data set in one task might be not compatible with the formula    specified in the learner
   
2. Integration of the formula into the task
```r 
classif.task = makeClassifTask(data = df, target = "target", formula = "target ~ s(p1) + s(p2)")
```
   - The task could be used just with one specific learner
   - Benchmark would also fail if the formula specified in the task is not compatible with the classifier
   

In our discussion @pat-s came up with a new solution. A task could store a named vector with the classifier name and the associated formula. 

```r
# Create named vector
formula_vector = structure(c("target ~ s(p1) + s(p2)", "target ~ p1 + (1|p2)"), names= c("classif.gam", "classif.glmmPQL"))

# Set in task
classif.task = makeClassifTask(data = df, target = "target", formula = formula_vector)
```

`getTaskFormula()` could be used to return a formula if there is a matching one for the specified learner.

This solution has the advantage that

+ It is possible to use different learners with one task
+ Benchmarking would still be possible
+ We keep somehow the spirit of MLR that the task defines the formula. It would be even possible to force the user that the formula contains all columns of the data frame like it was always done with the automatic generated formula. 

If we can agree on this solution, I would start with the implementation and add `gam` and `glmmPQL` later.

**Comment by mb706** [comment]
Some thoughts:

* Having the formula (which clearly changes `Learner` behaviour) in the `Task` makes it impossible to tune over.
* So far, a `Task` was `Learner`-agnostic, this would change that.

OTOH I can't see any alternative solution that is actually elegant.

**Comment by pat-s** [comment]
> Having the formula (which clearly changes Learner behaviour) in the Task makes it impossible to tune over.

Why is that? Isn't `getTaskFormula()` called in the tuning step? If not, there is certainly a different way to also get the formula from the task in the tuning step.

> So far, a Task was Learner-agnostic, this would change that.

There are only two options: Add it at the learner level as a param as done in my mgcv::gam implementation (which is also not elegant as the formula is not a actual param) or add it at the task level (which would change the learner-agnostic of the Task, yes). 

This feature has been missing for way too long and prevents the implementation of a lot (mainly parametric) algorithms.

**Comment by pat-s** [comment]
@berndbischl @larskotthoff @mllg @jakob-r 
Would be great if you could write down your thoughts on this.

@mb706 
Could you explain the issue with the tuning in more detail?

**Comment by mb706** [comment]
The tuning problem I am referring to is the question of *which* features should be approximated by a smooth function (i.e. should have `s()` in the formula). One cannot use `tuneParams()` to do that, if the formula is part of the task and not in some way specified by parameters. So while it is possible to perform tuning of *unrelated* parameters, tuning of the *formula itself* would not work.

Since one of the great assets of `mlr` is the possibility to take any learner and any subset of its hyperparameters and plug them into `tuneParams`, I would be careful with introducing features that break this.

---
Just having the formula as a parameter is still a suboptimal solution for tuning, since it would only allow tuning using a search space involving something like `makeDiscreteParam(values = list(formula1, formula2, ...))`, i.e. enumerating all candidate formulas.

A nicer solution would probably be to have a `LogicalVector` parameter with dimension `NA` that specifies, for each feature, whether it should be wrapped in `s()` or not. (Aside: I don't know `gam` so well. If there are different options for approximation of each feature, one could use a `DiscreteVector` instead of a `LogicalVector`, with the discrete values enumerating the different possibilities by which a feature can be modified in a formula.) This kind of parameter is not without precedent, see for example the `xvar.wt` parameter of `randomForestSRC`, or the `split.select.weights` for `ranger`, both of which specify sampling probabilities for each feature.

The dependence of the search space on the feature setup is still not very nice; the difference here is obviously that while `xvar.wt` is only peripheral for `randomForestSRC`, while whether or not to place `s()` is very central for `gam`. A *good* solution might be *somewhere* out there, we just need to find it...

---

As I understand the idea behind the `Task` object, it is supposed to be just data with some relatively general meta-information: What is the target feature, how should the data be resampled. It answers the question "What do we know about the data that we are working with?". How someone decides to work with this information should be reflected on the side of the chosen `Learner` (and its hyperparameters). If there is some general, learner-independent way to frame the information that should go into the formulae (maybe the nesting relationships for mixed models? Insofar as different learners, or possibly wrappers, could make use of this information), then I think this informaiton could reasonably be placed in the tasks. Also, if a formula is in some way generally used by every learner, it can arguably be placed in the task (which would probably be equivalent to creating a new task with the `model.matrix` generated from this formula). Changing the behaviour of a `Task` depending on the type of a `Learner` breaks down these concepts of `Task` and `Learner`, which is usually not a good sign.

**Comment by pat-s** [comment]
> As I understand the idea behind the Task object, it is supposed to be just data with some relatively general meta-information: What is the target feature, how should the data be resampled. It answers the question "What do we know about the data that we are working with?". How someone decides to work with this information should be reflected on the side of the chosen Learner (and its hyperparameters). If there is some general, learner-independent way to frame the information that should go into the formulae (maybe the nesting relationships for mixed models? Insofar as different learners, or possibly wrappers, could make use of this information), then I think this informaiton could reasonably be placed in the tasks. Also, if a formula is in some way generally used by every learner, it can arguably be placed in the task (which would probably be equivalent to creating a new task with the model.matrix generated from this formula). Changing the behaviour of a Task depending on the type of a Learner breaks down these concepts of Task and Learner, which is usually not a good sign.

I agree on that.

> Just having the formula as a parameter is still a sub-optimal solution for tuning, since it would only allow tuning using a search space involving something like makeDiscreteParam(values = list(formula1, formula2, ...)), i.e. enumerating all candidate formulas.

The idea of `mgcv::gam` is not that it should be "tuned" with different values in `s()` but that a large enough number needs to be supplied for each predictor so that the model has full flexibility while still having an acceptable runtime (the > k, the longer runtime).
If you would tune `mgcv::gam` with mlr and its formula, you would essentially do a "tuning of the tuning" as `mgcv::gam` does that internally.

---

So it seems to tailor down to parametric models that have (in any way) a complicated approach to perform an internal tuning. 
Essentially, to make it work with the mlr tuning idea, we would need to suppress the internal tuning by default and offer possibilities to do so using all existing tuning methods of mlr. 
However, that means that we would need to catch the supplied arguments within `s()`  and then run our own optimization (mbo, cv, etc.). 
I don't think this is the way to go and has any added value.
The major point for most users when using `mgcv::gam`  is just to have a single interface to compare it to other algorithms (benchmarking) on the same resampling objects (e.g. CV) with the pre-defined "optimal" settings of `s()` and everything else in the formula.

All the options provided by `mgcv::gam` are not simply tunable but need to be chosen according to the task. 
Usually, there are only few settings that make sense for a given task. 
And these are mainly stored within the task while other parameters are handed over as simple "hyperparameters", such as the selection of the optimization method etc. 

I think this general idea of having a parametric model specified with "expert knowledge", and only using mlr as a consistent interface to use the model, can be applied to many more parametric models.
So in the end, if we agree on that, it might be easiest to accept that such models need a formula argument because a lot of their internal settings are stored within its formula.
And yes, then the `formula` would be treated as an discrete hyperparameter that could also be tuned in theory (as a full formula).
HOWEVER, usually the user who knows what he is doing does not do that because he is aware of facts like the saturation effect of `k` mentioned above. 
All these models with a formula parameter should not be tuned, they should just be selectable at all to do "train, predict, resample".
If we agree on the just mentioned approach, the already existing PR #1899 which has `formula` as a parameter would be the way to go. 
(As a side note, I (and others at our department) use this implementation successfully since months and are completely satisfied with it as the major requirement is in benchmarking.)

> Aside: I don't know gam so well. If there are different options for approximation of each feature, one could use a DiscreteVector instead of a LogicalVector, with the discrete values enumerating the different possibilities by which a feature can be modified in a formula.)

There are multiple tuning options of `s()`, yes. All explained in mgcv::smooth.terms`.
This would be one option of "tuning the formula" which however is not needed because there are reasons why specific settings are set in `s()` depending on the task.

**Comment by pat-s** [comment]
We decided to not implement this in _mlr_ for now and focusing on getting it working in _mlr3_: https://github.com/mlr-org/mlr3/issues/237.
