### ISSUE TITLE
Discuss the changes in #2099

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#2204]
https://github.com/mlr-org/mlr/pull/2099

https://github.com/mlr-org/mlr/commit/ed18b6abdbd245509a1fc573dd6cf31655c0bf2d

**Comment by mb706** [comment]
The problem here is that learners that don't have the "missings" property show one of three behaviours:
1) Actually is able to do predictions with NA features
2) Does not handle NA features during prediction, but makes NA predictions for affected rows
3) Does not handle NA features during prediction and actually returns an error when they are present

#2099 tries to avoid 3) by forcing the behaviour in 2). There are only very few of kind 1), so this may or may not be an acceptable tradeoff (and having a `"missings.predict"` or so property would help). Behaviour 3) is annoying, however, especially when unseen classes are turned into NAs.

**Comment by pat-s** [comment]
Discussion ported to _mlr3_.
