### ISSUE TITLE
Upcoming ggplot2 v2.3.0 will possibly break plotTuneMultiCritResult

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2231]
Line 103 in https://github.com/mlr-org/mlr/blob/master/vignettes/tutorial/devel/advanced_tune.Rmd

```r
plotTuneMultiCritResult(res)

traceback()
14: stop("A continuous variable can not be mapped to shape", call. = FALSE)
13: scale_f()
12: find_scale(aes, datacols[[aes]], env)
11: f(..., self = self)
10: scales$add(find_scale(aes, datacols[[aes]], env))
9: scales_add_defaults(plot$scales, data, aesthetics, plot$plot_env)
8: f(..., self = self)
7: l$compute_aesthetics(d, plot)
6: f(l = layers[[i]], d = data[[i]])
5: by_layer(function(l, d) l$compute_aesthetics(d, plot))
4: ggplot_build.ggplot(x)
3: ggplot_build(x)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

Works with the current CRAN version of `ggplot2` (2.2.1)

**Comment by pat-s** [comment]
`ggplot2` v 2.3.0 is said to be released on June 26. We should tackle this issue in more detail until then.

**Comment by jakob-r** [comment]
This is because we construct the mapping with `aes_string(shape = NULL)`. This worked in the past and should be expected to work in the future as well. They have worked on the mappings but but as I tried it now it also works for the latest devel of ggplot2 so everything should be fine.
@pat-s Can you confirm and close if so

**Comment by pat-s** [comment]
Indeed, works again. So it was just a temporary thing during development. Thanks @jakob-r!
