### ISSUE TITLE
plotLearnerPrediction: should also work when models are trained on > 2 features?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#231]
I guess this is still useful, we simply visualize the pred for only 2 selected features?
Maybe think about it? What about partial dependecy plot?

**Comment by berndbischl** [comment]
Can we also a cool 3D plot for 2d regression? would like nice.

**Comment by Autodidact24** [comment]
@berndbischl,
We are using ggplot which supports partial dependency plot and 3D plots.
Lets first discuss how we can integrate other dimensions.
Do we still want 2 selected features as default and be able to select more ?

**Comment by berndbischl** [comment]
> We are using ggplot which supports partial dependency plot and 3D plots.

Can you post a link for these please?

**Comment by berndbischl** [comment]
@Autodidact24 

I think it is best to implement a 3D plot for regression problems R^2 ---> R . 
So like this, and rotatable:
http://www.agocg.ac.uk/reports/graphics/34/appii97/image21.gif

Of course R supports this, the major problem is to find the "best" package for this.
If ggplot2 can do this, even better! 
I didnt know that.

**Comment by berndbischl** [comment]
Regarding > 2 input dimensions:
That is why I mentioned partial dependency plots.

Let me explain a bit more. We currently only support models fitted on maximally 2d input data.
Which is already nice for teaching and exploration. But I might also want to visualize a "real" model.
Of course, I cannot have more than 2d for the input space. So I need to specify what to do with the other dimensions. Usually one "integrates" them out.

http://scikit-learn.org/stable/auto_examples/ensemble/plot_partial_dependence.html

**Comment by zmjones** [comment]
[edarf](https://github.com/zmjones/edarf) and with [ggRandomForests](https://github.com/ehrlinger/ggRandomForests) both do partial dependence calculations, the former for `cforest`, `rfsrc` and `randomForest` and the latter only for `rfsrc`. 

It would be nice to extend this sort of functionality to all supervised methods, along with the ability to average over whatever part of the feature space the user requires (including ones that aren't ammenable to plotting). Plotting 2D objects is of course easy with `ggplot2` but if you want partial dependence of more than one feature jointly you can plot one and facet on the other, or colour it, etc. I also think you can do these sorts of plots with regression, classification (class and probs), and survival. [This](https://github.com/zmjones/edarf/blob/master/README.md) is the sort of thing I've generated so far.

It would also be nice to have an option to not average over the other features and just get a marginal measure: this would be much faster and useful sometimes for exploration.

Currently all the stuff in `edarf` is done in R with parallelization via foreach/doParallel, but I think a lot of it could be rewritten in C++ so that the only real bottleneck would be getting the predictions from the fitted object at each iteration.

It also might be nice to have at least a warning when using `plotLearnerPrediction` with more than 2 features. I tried it with a bunch of features and it ran for a while and then eventually failed with an opaque error message.

**Comment by larskotthoff** [comment]
It would also be nice to combine this with a way of automatically finding the most "interesting" (e.g. predictive) features and display those. This would make it much easier for the user as you don't have to guess and wade through scores of graphs.

**Comment by berndbischl** [comment]
@larskotthoff 
We kinda already have that as can do eg feeature filtering before and rank them?

If we add more in the way of feature importance measuring in mlr, you also have something "model dependent"

**Comment by larskotthoff** [comment]
Yep, model-dependent is what I mean -- the current ranking may or may not be meaningful for the actual model.

**Comment by berndbischl** [comment]
For feature importance I had asked @ljudt to do something in his masters thesis work.

**Comment by berndbischl** [comment]
I would also be good to display multiple plots with facet_wrap for multiple features / multiple feature pairs.

**Comment by berndbischl** [comment]
for 3d plots, package plot3d might be best, should be investigated

**Comment by berndbischl** [comment]
@zmjones 
Can you simple write some feedback here? Not nagging, just asking about status quo

**Comment by zmjones** [comment]
So if you wanted to facet are you saying you'd want to train on different pairs and then plot the results using facetting?

I am not sure plot3D is best but investigating this is on my to-do list.

I get the purpose of this function for teaching but I still sort of want to split it into multiple functions. Maybe we could have a plotDecisionBoundary function which takes some sort of prediction and then makes a similar plot based on some subset of the features. We could just say in the docs that you need to train on 2-3 features if you want a nice plot. This could work with partial predictions as well.

**Comment by berndbischl** [comment]
Issue #509 is very related, maybe even the same.
Does it help if we, @larskotthoff and @zmjones, talk next week to get some structure into this?
Might be easier to discuss on hangout?

**Comment by larskotthoff** [comment]
Yep, I think it would be a good idea to talk about this. I'm available pretty much all of next week except Monday.

**Comment by berndbischl** [comment]
Wednesday 19:15 CET? After the other talk?

**Comment by larskotthoff** [comment]
Fine by me.

**Comment by zmjones** [comment]
Yep I think this issue is a subset of #509. I am hopefully going to have some time to work on this this week. Yes I can talk then though I have a class at 20:15 CET.

**Comment by zmjones** [comment]
Closing in favor of #509
