### ISSUE TITLE
Travis + TIC = Mess

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2424]
The following happened:

Travis + TIC deployed into the master branch and touched code(!).
e.g.: https://github.com/mlr-org/mlr/commit/da3081d8af0f064400fccc42948852ac525989c8

This cannot happen!

Why did it happen?
My theory: 
* Commit A triggered Travis
* Travis cloned at stage A
* Now Commit B comes while Travis A is still running
* Travis is triggered and clones at stage B
* Now Travis A deploys and overwrites all master changes (effectively reverting B)
* Now luckily Travis B finishes and overwrites those changes. (repairing the revert)

Some things did not get repaired, though. @berndbischl and I hopefully repaired that.

We also deactivated the deployment.

@pat-s 
* Please restrict the deployment of tic to the gh-pages branch, which should be doable in `step_push_deploy()`
* Maybe let the tic developers now that those strange things can happen. 
* Why does it say `branch: master` in the deploy section of `.travis.yml`?

**Comment by pat-s** [comment]
The reverting issue is fixed in the most recent GH version of tic. We still use my fork which is not updated yet.

I'll explain it in more detail later. Currently on vacation without my lap until Sunday.

**Comment by pat-s** [comment]
A bit more detailed now. No cross-references as I am writing from my phone. 

The "reverting" is a known issue in tic and is already solved in the most recent master. Since we faced this issue last time, we changed from tic deployment to the old approach for the deployment of `man/` and NS. 

The reverting happens if there are multiple commits having a race in master on travis. 

It does not happen when making an orphan commit to GH-pages. 

**Why did I change the pkgdown deployment to master?**

Because this enables PR previews of the tutorial via netflify. 

**Why did the reverting happen again?** 
1. I did not think of the issue when making the change serving the tutorial from the _master_ branch instead of _gh-pages_. 
2. We are using a fork of tic currently that doesn't have the latest fix yet

**how can we solve the situation?** 
1. Update the fork and everything should be fine
2. Or going back serving the tutorial from the _gh-pages_ branch and losing the netflify PR previews again.

**who is responsible for that?**
In the end me, because I made the change to serve the docs from master which triggered the race condition and did not update my fork with tic upstream that already has the fix.

**Comment by pat-s** [comment]
It was fixed in https://github.com/ropenscilabs/tic/issues/45#issuecomment-411900627 and is now also merged into my fork.

> But if possible, we should also ensure that this cannot happen again (see "rights" in 2)

This is a bit problematic. Its not about `tic` or not `tic` here, as long as we allow any automatic deployment to `master` from Travis (e.g. man/, NS or the tutorial) this can potentially happen. 

However, we want Travis to do the work here so we have to "trust" Travis somehow. Again, `tic` does nothing more than just doing the same kind of deployment as we had before with the manual git approach. The race condition issue a bit complex as the git base of the repo changes when multiple commits are pushed at the same time.

As deployment should be safe now again, I close here. Feel free to continue the discussion if there are still open questions!
