### ISSUE TITLE
training RandomForest is incredibly inefficient..

### ISSUE THREAD

**Issue by caprone** [mlr-org/mlr#2458]
HI
why training RandomForest is incredibly inefficient...? very time consuming (around 7 time slower than sklearn implementation!!!) and inefficient ram usage...??

RF in one of fundamental algorithms in ML...but in this way it's impossible use it (and I dare not think if you need  tuning, resampling or ensembling with RF..);

ther's a different package in R at least decent??

**Comment by caprone** [comment]
ohh, Perfect..thanks for advice!

**Comment by caprone** [comment]
sorry, I have to review my judgment..(I was taken by enthusiasm to see a parallelizable rf package );

I tried RandomForestRegressor' sklearn with same data amount, but with more estimator (trees) than in ranger;
also i setted 8 threads in ranger, (instead sklearn works in sequential mode not in parallel)..and incredibly sklearn implementation was even more faster than ranger!!; R packages have a Embarrassing computational inefficiency;

Then,  how it possible that R packages are as slow??? there is someone who works 'pro' on big data with R??? sincerly I don't think it's possible...

i take 3 days to look at R (I already knew discretely) and mlr package for big -data mining...
this package seems great!, good flexibly, scalably and customizable; ther'snt equivalent on python, but seems me that on big data that effort will be 'useless...no???

**Comment by mb706** [comment]
Most of the interesting computation happens in fast `ranger` cpp code, the inefficiency introduced by R / mlr is mostly just the conversion from mlr "Task" / `data.frame` to (as used by ranger internally) matrix. You can try to call `ranger::ranger` directly with data in matrix format to see if it improves things.

If there is a large discrepancy in performance it may be because
1) you are training many models using small datasets that makes the overhead introduced by R/mlr relatively more severe, or
2) you are using a small value of `num.trees` that reduces the relative time spent in model training code (and again, makes R overhead more prominent), or
3) You are using different parameters in R and sklearn (different number of trees, different maximum tree depth, ...) that invalidate the comparison.

R in general can indeed be relatively slow, although you should really consider the time and cost you spend  writing code (which can be quite fast in R) in addition to the time and cost of running computation. R + mlr may (or may not) win out in the end here.

**Comment by caprone** [comment]
HI and thanks for comprehensive answer;
yes I'll try call ranger in matrix frmt to chek some improvement, thanks;

of course I compared with same parameters  and I trained only one model to experiment with;
Nevertheless I'm trying to test different shallow algorithms, like gbm, xgb and others.. in mlr framework , and  performances seems very acceptable!! 

as already mentioned this package seems very powerful! I will investigate further ;)

thanks for your support

**Comment by pat-s** [comment]
Thanks Martin for the explanations.
