### ISSUE TITLE
logloss requiring predict type to be "prob" when it is already "prob"

### ISSUE THREAD

**Issue by rsangole** [mlr-org/mlr#2496]
# Code

```{r}
set.seed(42)

# Common definitions
parallelMap::parallelStart(mode = "multicore", cpus = 31)
meas_multi <- list(mmce, kappa, logloss)
(rdesc <- makeResampleDesc(method = "CV", iters=5, stratify = TRUE))

tsk1 <- makeClassifTask(id = "base", data = df_hyp1_base_train, target = "cover_type")
tsk2 <- makeClassifTask(id = "h1",   data = df_hyp1_train, target = "cover_type")
(lrn1 <- makeLearner(cl = "classif.xgboost", id = "model1_xbg", predict.type = "prob",
                    verbose = 1,
                    early_stopping_rounds = 20,
                    nrounds = 50L,
                    eta = 0.3,
                    max_depth = 10))
(lrn2 <- makePreprocWrapperCaret(learner = "classif.xgboost",
                                id = "xgb_pca",
                                predict.type = "prob",
                                verbose = 1,
                                early_stopping_rounds = 20,
                                nrounds = 50L,
                                eta = 0.3,
                                max_depth = 10,
                                ppc.pca = TRUE,
                                ppc.thresh = 0.8))

bmr_h1 = benchmark(learners = list(lrn1, lrn2),
                   tasks = list(tsk1, tsk2),
                   resamplings = rdesc, measures = meas_multi, show.info = T)
```

# Console out

```
Mapping in parallel: mode = multicore; cpus = 31; elements = 4.
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 2 slave jobs, displaying at most 10 of them:

00003: Error in FUN(X[[i]], ...) : 
  Measure logloss requires predict type to be: 'prob'!

00004: Error in FUN(X[[i]], ...) : 
  Measure logloss requires predict type to be: 'prob'!
```
Why do I get an error when the predict type is already set to `prob`?

**Comment by pat-s** [comment]
Have you tried a different learner? Haven't faced that prob with `xgoobst`. 

Also the [reprex](https://github.com/tidyverse/reprex) pkg is great for reproducible examples. 

Haven't used `makePreprocWrapperCaret` yet, does it also occur if you only use `lnr1`?

**Comment by mb706** [comment]
The problem here is that the arguments given to `makePreprocWrapperCaret` (and also `makePreprocWrapper`) are *not* used to set up the underlying learner, but only the preprocessing options. When calling `makePreprocWrapper`, you should give a learner that already has its desired parameters and `predict.type`. (What is happening here is that `makePreprocWrapper` uses the `"classif.xgboost"` string argument to construct a vanilla `classif.xgboost` learner, but gives all further arguments to the Caret preprocessor, which ignores the `predict.type` argument and most others. Ideally `mlr` should complain in this case, see #2497).

The following should hopefully work as you expect:
```r
[...]
lrn2 <- makePreprocWrapperCaret(lrn1,
                                ppc.pca = TRUE,
                                ppc.thresh = 0.8)
[...]
```
(This will give `lrn2` the ID `model1_xgb.preproc`; if you're unhappy with that set it using `lrn2$id <- [...]`.)

**Comment by rsangole** [comment]
Thanks @mb706 I'll try this out.

**Comment by mb706** [comment]
I'm assuming this solves your issue, but feel free to respond if you have further questions.
