### ISSUE TITLE
Tests: Equality checks fail on macOS due to tolerance arg

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2667]
I was just playing around a bit with macOS on Travis on the side and recognizing that some tests fail there due to the tolerance value in tests which do equality comparisons: https://travis-ci.org/mlr-org/mlr/builds/603041392#L924

The same tests pass on all of our Linux CI runs (both circle and travis).

I can also reproduce the errors locally on my Mac. Are there differences in RNG & friends on macOS?!

cc @berndbischl @mllg

**Comment by mllg** [comment]
It is possible that there are some numerical differences (clang instead of gcc, vecLib instead of reference blas / openblas, ...). But this would only matter for cross-platform comparisons (i.e., hard-coding some results from a linux box in the tests). The failing tests compare the results of two ranger calls on the same mac os system.

Try to use exactly the same hyperparameters in the test. AFAICT the tests don't set `num.threads = 1L` or `verbose = FALSE`. Additionally, the tests use the formula interface while the learners use the matrix interface.

None of this should be responsible for a test failing. This could eventually be a bug in ranger, but I guess you have to narrow it down further to make sure.

**Comment by mllg** [comment]
FWIW, I don't see any problems on Mojave (R from homebrew/cask, pre-compiled binary from CRAN).

**Comment by berndbischl** [comment]
do we really have to consider testing on macos? how about we ignore this?
i see about zero chance that if we detect something there, that the problem is due to us

**Comment by pat-s** [comment]
Even if its not due to us we should understand what's going on and why it happens. At least because of reproducibility. 

I can also reproduce the errors locally (also on Mojave, official R binary). I have to check my compilers as I switch between gcc, clang and llvm permanently (reason: some pkgs (like data.table) can only be build with one of them).

Yes its tedious but why should we ignore system-related issues? That's the whole purpose of testing on different systems -> to somehow mingle with their specialties even if the problems are not directly coming from our code. But the OS-specs won't change so we have to adapt (not saying how we should do that).

**Comment by berndbischl** [comment]
we should not ignore. but its a matter of ressources. and also whether we can (likely) do something about this

**Comment by berndbischl** [comment]
try it out, and see if you can figure this out

**Comment by pat-s** [comment]
See https://github.com/imbs-hl/ranger/issues/451

**Comment by pat-s** [comment]
Fun fact: While I now do not see any differences anymore in our tests, the [ranger reprex](https://github.com/imbs-hl/ranger/issues/451#issue-514988837) still shows differences for me (all in a new session).
I've now tested this 3 times and meanwhile I'm confused.

Essentially, the test in mlr does exactly the same as the reprex (`w.allone` is just a vec of length `train.inds` with all "1"s.)

https://github.com/mlr-org/mlr/blob/4131bcc4049403f7435a9b2aefba6bfe064a2fc1/tests/testthat/helper_learners_all.R#L25-L31

**Comment by pat-s** [comment]
Fixed [upstream](https://github.com/imbs-hl/ranger/issues/451) in _ranger_.

Also I am hesitant right now to test on macOS, mainly because of the slow startup times of the service.
