### ISSUE TITLE
mlr _R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check errors

### ISSUE THREAD

**Issue by rsbivand** [mlr-org/mlr#2724]
Many of the suggested packages are not protected by warnings or messages if not installed, and R CMD check is run without requiring the presence of these packages. I run regular reverse dependency checks for spatial packages, here **sf**, and your omission causes many unnecessary installs. I'm aware that **mlr** is sunset re: mlr3, but tidyness in not throwing errors when checking without suggested packages being available is very good practice.

**Comment by pat-s** [comment]
We usually have 

https://github.com/mlr-org/mlr/blob/b57049d9ae4b73b8de7d012d648e7cca9a6478bc/R/createSpatialResamplingPlots.R#L130-L130

for all functions using suggested packages.

> but tidyness in not throwing errors when checking without suggested packages being available is very good practice

I don't understand this. Can you clarify?

Also could you be more specific in what error is thrown in your revdepchecks?

I could add `skip_if_not_installed("sf")` to the one test in {mlr} which relies on {sf} if that helps. But I still do not fully understand the problem yet.

**Comment by rsbivand** [comment]
I am running reverse dependency checks on **sp**, **rgdal**, **raster** and **sf**, almost 900 packages. One of these is **mlr**. Because it suggests **sf**, I run the revdep check on **mlr** with the development version of **sf** built against new versions of external software used by **sf**, to test whether changes in the upstream external software against which **sf** is built impact downstream packages like **mlr**.

If I run the checks with `_R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check ...`, of the almost 900 packages, **mlr** is one of two to fail because you do not provide support for running checks without the suggested packages. You should never write examples or tests that error exit when the only "error" is the lack of a suggested package, since suggested packages are never mandatory. Both code, examples and tests should at most issue a warning if `requireNamespace()` or `require()` return FALSE when the package is not found. Try yourselves to make a fresh install on a bare system without pulling in suggested packages, then try R CMD check (fails immediately because of missing suggested packages). Use the environment variable `_R_CHECK_FORCE_SUGGESTS_=FALSE` to avoid the burden of handling uninstalled suggested packages, and the check should pass, but **mlr** fails predictably unless all the many suggested packages and their dependencies are present. I do a lot of revdep testing to try to protect downstream packages from changes upstream of spatial packages, but my life is made much harder trying to see why packages fail when the failures are caused by not following specifications (packages should check cleanly  without suggested packages available).

> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms. (‘Writing R Extensions’ recommends that they are always used conditionally.)  - https://cran.r-project.org/web/packages/policies.html

> The ‘Suggests’ field uses the same syntax as ‘Depends’ and lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes (see Writing package vignettes), and packages loaded in the body of functions. E.g., suppose an example11 from package foo uses a dataset from package bar. Then it is not necessary to have bar use foo unless one wants to execute all the examples/tests/vignettes: it is useful to have bar, but not necessary. Version requirements can be specified but should be checked by the code which uses the package. (WRE).

I guess this affects your **mlr3** iteration, so you may choose not to fix this, but it may lead me simply to stop testing **mlr** for negative consequences of its use of **sf** when the software upstream of **sf** (GDAL/PROJ) changes radically - as it is now doing.

**Comment by berndbischl** [comment]
sure we fix this here, we are running enough rev-checks ourselves, care about proper testing, and certainly dont want to hurt other people of the same mindset.

does this problem occur in testing mlr examples, unit tests, or both?

**Comment by berndbischl** [comment]
> I could add `skip_if_not_installed("sf")` to the one test in {mlr} which relies on {sf}

thats not enough, he needs us to ensure this for all suggested packages, and this also needs to be checked for all examples

**Comment by rsbivand** [comment]
Thanks! In this case I couldn't hang around and just installed all the suggested packages, but then I run revdeps on my desktop, not in an instantiated container. To do revdeps on the four spatial packages involves almost 20% of CRAN plus a few BioC packages, so putting those onto a container that needs refreshing for each use isn't much fun. Life would be leaner if running examples, tests, vignettes etc., didn't require code to be run where the unavailable suggested packages don't interact with the package being revdep checked (and its external software components); the packages being revdep checked are obviously available, so code should run if they are available. I can't work around calls to the package being revdep checked being inside a prior condition on another package, but that's a chance I can live with. So conditioning everything in suggested and enhanced may be helpful anyway, when you have the opportunity.

**Comment by pat-s** [comment]
All majors test platforms (CRAN / CI systems / revdepcheck pkg) run R CMD check after installing all dependencies (including suggests).

I just ran `R CMD check` in an isolated `renv` environment without all suggested packages and got **no** errors in the examples.

There are tests however, including the one which relies on {sf}, which are missing the `skip_if_not_installed("sf")` flag. That's why you error here.

Thinking about it again, I don't really understand why you are running revdepchecks without installing the suggested packages of the reverse dependencies. 
- If your package is within SUGGESTS of the rev dependency and the package is configured to skip examples/tests of suggested pkgs, then your check is pointless because no code using your package will be run at all.
- If you do not install the suggests, you risk that other tests unrelated to your package will error giving you more troubles

Exactly this happens when you revdepcheck {mlr} from the base {sf} or any other package:
- due to runtime reasons, the example of the function using {sf} is within `\donttest()` and hence won't run 
- if we prefix the test with `skip_if_not_installed("sf")`, the test would not run

You still did not say why you errored. But if its because of missing suggested packages that cause test failures, skipping those tests in a verbose way would not give you any hint if there was a "change to worse". Instead, you **want the tests/examples to be run** to see if there is a change.

So essentially, the whole effort of running the {mlr} checks because of {sf} would be pointless.

Instead, I'd say that all suggests should be installed in revdepchecks as otherwise a lot of examples/code won't even run.

One should only use `skip_if_not_installed()` if there are problems due to
- the R package not being available for certain R versions
- the R package not being available on certain OS

We are doing exactly this in {mlr}, e.g. for packages {glmnet} (R-version related) or other problematic ones (like {RWeka} which is troublesome to install).

So in summary, I see no point on our side to change anything and would rather advise to always install suggested packages in revdepchecks.

Quoting "Writing R extensions 1.1.3"

> Then it is not necessary to have bar use foo **unless one wants to execute all the examples/tests/vignettes**

## Imports vs Suggests

Imo the major differences is that the packages in SUGGESTS should only appear in some functions of a package which can eventually be skipped because the user only wants to use some other partial functionality.
This is perfectly the case here since {sf} is only used in one function which takes care of spatial objects.
90% of the {mlr} users do not need this and hence 99% of packages importing {mlr} don't want to have this in their recursive dep chain.
The major advantage of doing so is that these packages will not be installed via `install.packages()` and hence the dep chain stays small.
There is no point of putting a pkg into Imports when its only being used in one or two places but in the same way comes with price of being installed by any package that imports this package again.

## The ideal scenario

... would be that revdepcheck only checks the functions/examples where the desired package is part of. This however is not possible. Hence, you need to check everything.

**Comment by rsbivand** [comment]
Note that **revdepcheck** is not archived on CRAN. My position is based on running checks over many years, so I only use my own script, and have always used the environment variable permitting the check to proceed without suggested packages available, usually with very little pain. I have also always implemented examples, tests and vignettes to bypass unavailable suggested packages. I had assumed that careful package authors avoided false check errors caused by unavailable suggested packages, but have installed a few such packages if need be (also from BioC) simply to allow my revdep checks to proceed, leaving it for the package maintainers to handle fall-out for the out-conditioned code should there be any. I have never ever seen such a large list of suggested packages, and installing the successive packages mentioned in error messages turned out to be fruitless - the only option was to install the lot, drawing in well over a hundred other packages for which I have no use at all, and which will now slow down every use of update.packages().

By the way, I really don't need to check everything. I can just release the GDAL3/PROJ6-7 compliant **rgdal** and Edzer can release the matching **sf** using the radically changed external software, and not bother to warn those whose workflows may be impacted. I don't need to discuss this, I just would have preferred **mlr** to protect those running checks from unavailable suggested packages, packages which  are not needed for the core functionality being revdep-checked.

**Comment by berndbischl** [comment]
Dear Roger,
the tone is becoming slightly unfriendly and condescending.

We have discussed this internally. 

What you describing is based on your personal experience, with non-official personal scripts. This I guess makes it mainly your problem, not ours.
And our position is that for checks / tests that these should be run completely, not partially. 
This is also what happens on CRAN.
And this implies installing all suggested packages - which might take some extra time, but can easily be automated.  CRAN does that, we do that, other parties we know do that, and in that case mlr checks/tests fine, and we never had general problems here. 
(IOtherwise please do file further reports)

Regarding your final point and paragraph: I would advise re-reading the CRAN policies here. But that's really between you and CRAN then. Good luck!

**Comment by pat-s** [comment]
> I have never ever seen such a large list of suggested packages, and installing the successive packages mentioned in error messages turned out to be fruitless - the only option was to install the lot, drawing in well over a hundred other packages for which I have no use at all, and which will now slow down every use of update.packages().

{mlr} is a special pkg in R because there is probably no package out there which so many pkgs in Suggests. Hence we understand the pain in install all required deps. 
This was also part of the motivation to split everything up in {mlr3}.

> By the way, I really don't need to check everything.

> By the way, I really don't need to check everything. I can just release the GDAL3/PROJ6-7 compliant rgdal and Edzer can release the matching sf using the radically changed external software, and not bother to warn those whose workflows may be impacted.

Yes, you do not need to check everything yourself. However, if you release an update, CRAN will run the revdepchecks for you and if there is a change to worse, ask you whether this is caused by your change and if the maintainers of the affected packages have been informed.

So yes, you **need** to warn/inform the affected packages.

You are of course free to exclude {mlr} from your list of private revdepchecks.
We just assume that you would stick to the policy of informing us if there would be a breaking change due to an update - if this is detected by a CRAN revdepcheck.

>  I just would have preferred mlr to protect those running checks from unavailable suggested packages, packages which are not needed for the core functionality being revdep-checked.

Our workflow is different here and we prefer to not protect the use of suggested packages in examples/tests just for this reason.
As much as we respect your decision to exclude {mlr} from your personal way of doing the revdepchecks, we would like you to respect our way of handling this.

Things might have changed (implicitly) in recent years regarding the practical usage of suggested packages and while the current state of suggested packages is certainly in a grey-zone right now, following the de-facto standard of the developer community helps to avoid painful situations.

**Comment by rsbivand** [comment]
@berndbischl OK, I'll back off, I do grasp CRAN policies, but am probably stricter wrt. dependencies. Good luck with **mlr3**.
@pat-s OK, I'll have to live with the de-facto status quo. The issue now is not that anything has changed in **sp**, **rgdal**, **raster** or **sf**, but that the upstream libraries that these all rely on are changing APIs and internal processes for defining coordinate reference systems and for transforming between them. This has already led to regressions, CRAN Debian check servers started using the new binary versions of the upstream libraries, and I'm trying to check on Fedora 31 with source installs of those libraries. So far from results run yesterday with new libraries and released **sf**, and overnight with the development version of **sf**, **mlr** is not affected. I haven't tallied all the affected packages for old to new external libraries, and old to new spatial packages, but I think the count of affected packages will be ~ 60. Issues have already been raised for most of these, say because previously adequate tests for equality of coordinate reference system definitions often break between old and new versions of the external libraries. The external libraries are being modernised to accommodate changes that continue to occur in the relative positions of points both between tectonic plates, and on the plates themselves, and all software using these libraries is scrambling to adapt to the process and API changes.
