### ISSUE TITLE
Bug in output value learner.model of train

### ISSUE THREAD

**Issue by TobiSonne** [mlr-org/mlr#2751]
Hello,

I want to use the output value `learner.model` of the result of `train`. In some functions I get the following error:

`Error in checkClass(x, classes, ordered, null.ok) : 
  object '.task' not found`

An example:

```
Data <- iris[iris$Species != "setosa",]
class(Data$Species) <- "character"
Classification.Task <- 
  makeClassifTask(data = Data,
                  target = "Species")
Learner.lr <- makeLearner("classif.logreg", predict.type = "prob")

Model.lr <- train(Learner.lr, 
                  task = Classification.Task)

lmtest::lrtest(Model.lr$learner.model)

```

I know I can additionally create the same with the `glm` function but this is not very smart in my opinion. And this output value should be exactly the same like the `glm`-result, shouldn't it?

Another luxury problem: Why can't I use a `data.table` or something similar (where `data.frame` is in `class`, too) in `createClassifTask`? This is a little bit annoying and (I guess) unnecessary.

Thank you for your help, great package anyway!

**Comment by pat-s** [comment]
`lmtest::lrtest()` is trying to do something with the `data` slot stored in the fitted GLM model. Here, `.task` is not available because this is an internal object used by mlr during training.

I don't think that `lmtest::lrtest()` makes a good choice here in doing so (I have never come across the package yet).

In any case, that is not an issue of {mlr} but rather in {lmtest} IMO trying to access the `data` slot of a fitted model.

``` r
library(mlr)
#> Loading required package: ParamHelpers
#> 'mlr' is in maintenance mode since July 2019. Future development
#> efforts will go into its successor 'mlr3' (<https://mlr3.mlr-org.com>).
mod <- train(makeLearner("classif.logreg", predict.type = "prob"),
  task = spam.task)
#> Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
lmtest::lrtest(mod$learner.model)
#> Error in checkClass(x, classes, ordered, null.ok): object '.task' not found
```

<sup>Created on 2020-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
