### ISSUE TITLE
Survival analysis using gbm

### ISSUE THREAD

**Issue by maozdd** [mlr-org/mlr#2775]
Thanks for the efforts with this amazing package.

I'm fitting a GBM with Cox Proportional Hazards model in dataset with right censored observations. I usually do this without mlr, but now I'd like to take advantage of the grid search function to find optimal tuning parameters.

I noted that the available options for the parameter of "distribution" in surv.gbm learner excludes "coxph". why is that? I don't think the provided options (bernoulli,adaboost,huberized,multinomial) are availble  for survival analysis.

Regards.

**Comment by pat-s** [comment]
I cannot help here since I don't know anything about survival analysis. The missing option could be for an internal reason or due to some new functionality upstream. You might need to check yourself.

I can only again suggest to use mlr3 and mlr3proba which has way better support for survival/probability learners.

**Comment by maozdd** [comment]
> need

Thank you very much for the fast reply!
