### ISSUE TITLE
listLearners should not need to load packages

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#361]
It annoys us. We only need this if Objects are used as defaults. We can work around this

**Comment by larskotthoff** [comment]
This turns out to be a thornier issue than I expected. The problem with simply introducing and passing an argument that tells `makeRLearnerInternal()` to not load the packages is that this would need to be passed through the entire call chain, i.e. adding the parameter in every single learner file. This seems like  an extremely hacky solution to me because the new parameter would appear all over the place.

A cleaner solution in my opinion would be to pull the metadata on the learners out from the closure into a data structure that could be used both during learner construction and when listing the learners. This should provide the same functionality, but much faster and more flexible.

Of course the parameters cannot be statically constructed because they may require the package to be installed and the user would get loads of errors when loading the package (unless we want to suppress them, which is probably not a good idea). So the `ParamSet` would still need to be inside a closure that is called when the learner is actually constructed and the package has been loaded. Apart from that it would also require significant changes to the internal architecture.

Thoughts?

**Comment by mllg** [comment]
If package-specific objects and functions are the only roadblock, how about just `quote()`-ing these arguments for lazy evaluation?

**Comment by berndbischl** [comment]
Would you check this for a moment? I currently cannot do this.

**Comment by berndbischl** [comment]
I might have a solution for this, which does only change listLearners and nothing else. I basically anlyse the code tree of the constructor S3 method and eval the properties only. This is much better than adding a further arg and also does not need to read the src file - which would not work for custom, locally added learner.

Would somebody look at this and help me with it if I push to a branch?

**Comment by larskotthoff** [comment]
Sure. I thought about this as well, but I'm not sure if this isn't going to break for some cases.

**Comment by berndbischl** [comment]
I have pushed a version of listLearners into the master branch.
That SHOULD already work. Can you please carefully check it and give some feedback?
