### ISSUE TITLE
3d plots for learner predictions

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#509]
Zach says:

> I don't think it will be that hard. I will try to find some time to work on
> it soon. I was thinking of making it something like
> plotPartialPrediction3D? plotLearnerPrediction could also use this of
> course, but I am in favor of splitting that up. Maybe then we could
> refactor to have plotPrediction, plotPredictionGGVIS, plotPrediction3D,
> plotDecisionBoundary, etc, which would take partial predictions or regular
> predictions and their use would only be restricted by the dimension of the
> associated feature space (which was either restricted to the correct number
> during training like in plotLearnerPrediction or the result of dimension
> reduction like the marginalization in partial predictions).

We could also have an argument to the plotting function that controls the number of dimensions shown and therefore the type of plot.

**Comment by zmjones** [comment]
So 3D plots probably are ineffective for multiclass classification. Should we explicitly exclude or just warn there? 

The only thing I dislike with having one unified function is that it requires a bit more work for the user to know what to expect it will do. It would have to be capable of plotting:

 - bivariate plots
 - grids of bivariate plots
 - facetted trivariate plots
 - 3d trivariate plots
 - trivariate (but 2d) decision boundaries plots

This would be pretty big at this point. I get the idea from a convenience stand point (this is after all for interactive/exploratory use) and I am not disagreeing that this is a good idea necessarily. Having them separate also requires the user to maybe do some digging. plotPartialPrediction can do the first 3 and is already not small. However maybe I could come up with a more abstract architecture which would make all of this more simple, i.e., maybe do both: have a set of simple functions the user can explicitly call or a bigger function which calls the individual ones as appropriate. Thoughts?

**Comment by larskotthoff** [comment]
I wouldn't exclude anything explicitly (just as we include learners which aren't necessarily good), but yes, mention in the documentation.

About the architecture: You raise a good point there. Do you think it would be feasible to have ggplot-style composability? I.e. something along the lines of

    plotPrediction(prediction~variable1+variable2, someData) + facet_3d(variable3) + facet_grid(variable4)

Would that make sense here? We should probably also thing about plots that are able to show potentially all dimensions (e.g. parallel coordinates) and how those could be incorporated into this "framework".

Having the bigger functions call the smaller ones is definitely a good idea and I would implement for this as far as possible.

Not saying that all of this needs to happen now :)

**Comment by berndbischl** [comment]
My 2cents:

1) Which current mlr plotters are interesting for 3D? 
Yes, plotLearnerPrediction and plotPartialPrediction. Yup, they are also very related, although not the same. (maybe plotLearnerPrediction is a bad name)

2) Should these 2 functions be further split up to generate a better, modular design?
Very likely yes. I would more care about added functionality here, because plots are more "endpoints", but it is still good idea to refactor this.

3) How should the plots look like, what is currently missing?
Well, from a purely user perspective, I want something like this, here from Matlab:
(for regression models)
http://www.peteryu.ca/_media/tutorials/matlab/image_surf_3d_basic.png
See the contour below the 3D area?
The plot should be rotatable and zoomable. 
Bonus points if I can easily get the contour plot on its own, quickly (?)

4) Which R packages come to mind?
So far I never remember having seen anything extremely great, but looking now at plot3d and plot3drgl, both seem to allow pretty closely what I want.

5) Classification?
I would try to focus on regression and binary classification first. Then lets talk whether this is extendable to multiclass or not. Lets push that decision back for now. I would say, it is, in a certain way, but that is an semi-educated guess.

5) One function on top level or multiple ones?
I guess 1 function will not work / is too hard too understand. But write down your ideas here before you start refactoring. We will figure out a good way toegether.

**Comment by pat-s** [comment]
-> mlr3?
