### ISSUE TITLE
Error when setting argument "replace" with classif.cforest

### ISSUE THREAD

**Issue by bkomboz** [mlr-org/mlr#556]
**Error:**
When I try to set the argument `replace` of learner `classif.cforest`, I get the following error when the tuning starts:

    Error in cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0,  : 
    formal argument "replace" matched by multiple actual arguments

**Minimal example:**

    library("mlr")
       
    lrn <- makeLearner("classif.cforest", predict.type = "prob",
                       par.vals = list(ntree = 1000, mtry = 5, minbucket = 10, maxdepth = 0, replace = FALSE))

    ps <- makeParamSet(
        makeDiscreteParam(id = "ntree", values = c(100, 200)),
        makeDiscreteParam(id = "mtry", values = c(5, 10)))
    ctrl <- makeTuneControlGrid()
    rdesc.inner <- makeResampleDesc("Subsample", iters = 5)
    rdesc.outer <- makeResampleDesc("CV", iters = 5)
    lrn.tuned <- makeTuneWrapper(learner = lrn, resampling = rdesc.inner, par.set = ps, control = ctrl)
   
    ## learning
    res <- resample(learner = lrn.tuned, task = pid.task, resampling = rdesc.outer)

However `getParamSet("classif.cforest")` tells me that `replace` is an argument of `classif.cforest`.

**Settings:**
R version: 3.2.2
mlr version: 2.5 (Github version)

**Comment by schiffner** [comment]
Thanks for the report.

* The error occurs because mlr uses `party::cforest_unbiased` as `control` option in
  `cforest` training, which already sets `replace = FALSE`.
  If the user also sets `replace` it gets specified twice in `party::cforest_control`, which
  causes the error.

* In your special case, as `replace = FALSE` by default, you can make this work by
  not setting `replace` at all, i.e.,

```
library("mlr")

lrn <- makeLearner("classif.cforest", predict.type = "prob",
                   par.vals = list(ntree = 1000, mtry = 5, minbucket = 10,
                   maxdepth = 0))

train(lrn, pid.task)
``

* Of course, we have a problem if someone wants to set `replace = TRUE` or change other defaults set by `party::cforest_unbiased`.
  I guess we should use `party::cforest_control` directly. We just have to think about which defaults we want.

@berndbischl, @larskotthoff: Do we want this for 2.5 or 2.6?


Some more information, i.e., a traceback and the definition of `party::cforest_unbiased`:

```
library("mlr")

lrn <- makeLearner("classif.cforest", predict.type = "prob",
                   par.vals = list(ntree = 1000, mtry = 5, minbucket = 10,
                   maxdepth = 0, replace = FALSE))

train(lrn, iris.task)
Error in cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0,  : 
  formal argument "replace" matched by multiple actual arguments
 1: train(lrn, iris.task)
 2: system.time(fun1(learner.model <- fun2(do.call(trainLearner, pars))), gcFirst = FALSE)
 3: fun1(learner.model <- fun2(do.call(trainLearner, pars)))
 4: fun2(do.call(trainLearner, pars))
 5: do.call(trainLearner, pars)
 6: (function (.learner, .task, .subset, .weights = NULL, ...) 
{
    UseMethod("trainLearner")
})(.learner = list(id = "classif.cforest", type = "cl
 7: trainLearner.classif.cforest(.learner = list(id = "classif.cforest", type = "classif", package = "party", properties = c("twoclass", "multicla
 8: learnerArgsToControl(party::cforest_unbiased, ntree, mtry, replace, fraction, trace, pvalue, teststat, testtype, mincriterion, minprob, minspl
 9: do.call(control, args)
10: (function (...) 
cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0, replace = FALSE, fraction = 0.632, ...))(ntree = 1000,
11: cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0, replace = FALSE, fraction = 0.632, ...)
```

```
party::cforest_unbiased
function (...) 
cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0, 
    replace = FALSE, fraction = 0.632, ...)
<environment: namespace:party>
```

**Comment by zmjones** [comment]
Why don't we just used `cforest_control` with the default arguments provided by `cforest_unbiased`?

**Comment by schiffner** [comment]
I agree. That would be my favorite solution, too.

**Comment by larskotthoff** [comment]
I've pushed a fix for that in #558.

**Comment by zmjones** [comment]
Speaking of defaults for tree methods, it makes little sense to me that the default for `mtry` (number of features randomly drawn at each node) is not data dependent. I know the hyperparameter gsco proposal had something about this in there. Can we do this now? It should be something like `floor(sqrt(getTaskNFeats(task)))`

**Comment by larskotthoff** [comment]
We can't do this in a "nice" way (i.e. specify this function in the "default" field), but we could certainly do it in the `trainLearner` function and add a note in the description.

**Comment by zmjones** [comment]
so just set a default argument in the train method and then a note in the learner definition about this?

**Comment by larskotthoff** [comment]
Yes. Of course only set it if it's not specified.
