### ISSUE TITLE
sometimes support packages that ONLY live on Github for now?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#661]
Hi,

what do you, other devels, think of this?
Here are three examples that come to my mind immediatly

1) 
https://github.com/swager/randomForestCI

2) 
https://github.com/mlr-org/mlrMBO

3)
At one point, xgboost was removed and only lived on CRAN.

My 2cents:

I would rather avoid interfacing such packages commonly, as must of them have a reason not to be on CRAN (eg because they are not finished). But for case like the above I would like to possibly make an exception, because we and other early adopters would like to use them "on our on risk".
(We could add a "warning" in the doc page in mlr for that interfacing method)
Also for 1) and 2) we already have doc anyhow, it simply lives in clumsy branches

So what are your thoughts? 
Will we run into trouble on CRAN if we do that (obviously we have to disable such a test for CRAN but can we get through R command check)?

Best

Bernd

**Comment by berndbischl** [comment]
@larskotthoff @mllg @zmjones @schiffner

**Comment by larskotthoff** [comment]
That's fine with me in principle, I don't see any disadvantage to supporting these as long as we label them experimental in the description and make sure that it doesn't break on CRAN (i.e. disable the tests). With devtools, installing from github is (almost) as easy as installing from CRAN, so the user doesn't have to jump through a lot of hoops.

I guess the development effort would be higher though because the API of such packages is more likely to change/break.

An alternative to including such learners in master/release would be to put each in their own branch (ready to be merged with a PR when the package is released) and have people install them directly from github. Given that the package needs to be installed from github as well, this would be quite reasonable I think. We would need to document this prominently and keep the list of learners that are available this way updated though (maybe in a separate section in the tutorial?).

**Comment by berndbischl** [comment]
> I guess the development effort would be higher though because the API of such packages is more likely to change/break.

Sure. But like I said, I would like to keep the instances were we do that down to a minimum anyways. We should always carefully ask ourselves:  "Do we need to support this? Now?" 
But for 1-3 above in the OP my answer would be indeed: "yes".

> An alternative to including such learners in master/release would be to put each in their own branch

I really dont want this is much:

a) Its too hard for too many people.
b) We already have many people installing mlr from Github, if we do stuff like that we just encourage it further.
c) Even for myself, as my "own user", I would find that a bit inconvenient / clumsy.
(I already noticed that in case 3) above for Zach RF "se" code)

**Comment by berndbischl** [comment]
I also emailed Uwe to ask whether we get into problems on CRAN if we do that.

**Comment by berndbischl** [comment]
Uwe said that this is allowed

Quote:

"Packages on which a CRAN package depends should be available from a mainstream repository: if any mentioned in ‘Suggests’ or ‘Enhances’ fields are not from such a repository, where to obtain them at a repository should be specified in an ‘Additional_repositories’ field of the DESCRIPTION file (as a comma-separated list of repository URLs) or for other means of access, described in the ‘Description’ field."

Uwe in German:
Also darf es hoechstens Suggests sein und dann per Additional_repositories deklariert sein. Wenn es nicht ein repository ist, mit dem install.packages() klar kommt (was natuerlich praeferiert ist), dann bitte in der Description schreiben, wie und von wo man das installiert.

**Comment by berndbischl** [comment]
lets hope we currently dont need this
