### ISSUE TITLE
The error message in a FailureModel is not stored for predictions?

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#668]
```r
configureMlr(on.learner.error = "warn")

lrn = makeLearner("classif.knn")
# randomForest stores the error messages
# lrn = makeLearner("classif.randomForest")
lrn$properties = c(lrn$properties, c("missings"))

task = sonar.task
task$env$data$V1[1:2] = NA
r = crossval(lrn, task)
r$err.msgs
```

```
   iter train predict
1     1  <NA>    <NA>
2     2  <NA>    <NA>
3     3  <NA>    <NA>
4     4  <NA>    <NA>
5     5  <NA>    <NA>
6     6  <NA>    <NA>
7     7  <NA>    <NA>
8     8  <NA>    <NA>
9     9  <NA>    <NA>
10   10  <NA>    <NA>
```

Shouldn't the `predict` column contain the error messages? Using `lrn = makeLearner("classif.randomForest")` for example stores an error message in the `train` column.

**Comment by larskotthoff** [comment]
The problem in this particular case is that the knn model only fails when predicting, not during training. For this we don't have any kind of error message saving in place at the moment -- the `predict` column of that data frame will always be `NA`.

I've added a new member `error` to `Prediction` and put any messages in there so that they appear in the appropriate place. This is in #784, please check.

That said, I'm not sure how useful this will be in practice as any errors that occur there are likely to be caught when building the model or checking the data and learner.
