### ISSUE TITLE
Package glmnet causes error when auc measure is requested

### ISSUE THREAD

**Issue by dominik-koch-tb** [mlr-org/mlr#669]
If **glmnet** is loaded after **mlr** then there will be an error when resample() is called.

```
Error in resample(learner = lrn, task = task, resampling = rdesc, show.info = FALSE,  : 
  Assertion on 'measures' failed: May only contain the following types: Measure
```
If **mlr** is loaded after **glmnet** then everythink works fine.

-----------------------------------------------------------

```R
library(mlr)
library(glmnet)

data(iris)

iris <- iris[iris$Species != "setosa",]
iris$Species <- factor(iris$Species)

## Define the task
task = makeClassifTask(id = "tutorial", data = iris, target = "Species")

## Define the learner
lrn = makeLearner("classif.glmnet", predict.type = "prob")

## Define the resampling strategy
rdesc = makeResampleDesc(method = "CV", stratify = TRUE)

## Do the resampling
r = resample(learner = lrn, task = task, resampling = rdesc, show.info = FALSE,measures = list(fpr, fnr, mmce, auc))

## Get the mean misclassification error
r$aggr
```

**Comment by berndbischl** [comment]
That is nothing we can solve. But you can work around it easily.

glmnet exports object "auc" as well. So you need to write: mlr::auc to select the correct object.
(Basically our error msg tells you exactly that).

Now, we would actually like to load glment via requireNamespace instead of require, and mlr usually does that for learners. Then the problem would not appear. But for glmnet we have an exception, because that does not work. In principle that means that glmnet's namespace is not correctly / perfectly defined. 
But we cannot do anything about this.

**Comment by berndbischl** [comment]
Hmm, I just tried to load glmnet with "requirePackages".  I guess it works now and they fixed it. I will do a PR.

Thx for the hint.

**Comment by dominik-koch-tb** [comment]
Thank you for the fast reply.
