### ISSUE TITLE
tuning: We store transformed x-vals in opt.paths. 

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#719]
But some part's in the code indicate that we actually want to store the original values.
What should we agree on?

**Comment by berndbischl** [comment]
what "parts"?

**Comment by jakob-r** [comment]
https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_tune_tuneGrid.R#L16-L27

**Comment by berndbischl** [comment]
hi,

this is getting old very quickly, please respond soon.

i really, like i posed before, dont understand this issue:

your title says this:

"tuning: We store transformed x-vals in opt.paths. "

that is wrong. pls check ?TuneResult, which is very clear about this
#' \item{opt.path [\code{\link[ParamHelpers]{OptPath}}]}{Optimization path which lead to \code{x}.
#'   Note that when you have trafos on some of your params, the opt.path always contains the
#'   UNTRANSFORMED values on the original scale. You can simply call \code{trafoOptPath(opt.path)} to
#'   transform them, or, \code{as.data.frame{trafoOptPath(opt.path)}}}
#' }

reason: because we can always call trafoOptPath on the op, but we cannot do the "backtranformation"

now if you know ANY example, where trafo'ed X-values are stored, please really do a proper bug report.

**Comment by berndbischl** [comment]
@jakob-r

**Comment by jakob-r** [comment]
Okay. It looks like I mistook some lines of code. But then I don't get why we set the value if we want to check for feasibility according to the hasTrafo.

**Comment by berndbischl** [comment]
Ok lets clear this up during our regular meeting tomorrow

**Comment by berndbischl** [comment]
jakob is right.

We ALWAYS store on untranformed scale, but the code actually makes it look like we sometimes dont and then disable check.feasible

IMHO check.feasible should always be T.

Can you pls do a PR?
