### ISSUE TITLE
classif.ksvm and classif.lssvm 'kernel' parameter has invalid option "stringdot"

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#739]
This seems to be a bug with documentation, since the help page mentions that "stringdot" should be an option. However:
```R
> train(makeLearner("classif.ksvm", kernel="stringdot"), pid.task)
Error in match.arg(kernel, c("rbfdot", "polydot", "tanhdot", "vanilladot",  :
  'arg' should be one of “rbfdot”, “polydot”, “tanhdot”, “vanilladot”, “laplacedot”, “besseldot”, “anovadot”, “splinedot”, “matrix”
Timing stopped at: 0.016 0.002 0.022
```
(similar with classif.lssvm).

As the output mentions, another option that would be available but is not offered by the ParamSet is `"matrix"`.

**Comment by tijoseymathew** [comment]
The error is actually being thrown by `kernlab` and not `mlr`. This is because the `stringdot` kernel is supported only by the list method of `ksvm`. The present `mlr` interfaces through the `formula` method which does not support `stringdot` kernels. 
The `matrix` kernel is not supported as per comments [Line 46](https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_ksvm.R#L46)
`ksvm` learner will probably need to be modified in some way.

**Comment by berndbischl** [comment]
we also dont support string data in anyform at the moment correct? 
So I guess we simply remove it.
