### ISSUE TITLE
review BMR merge functions. 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#747]
why do we actually have 2?

**Comment by giuseppec** [comment]
I have also written a single one function (I have it locally at my office) that uses those two and will do a PR on which @florianfendt can base his work. 
The reason why I used two function was this: 
1) assume you have 4 BMR with a) lrn.A and task.A b) lrn.B and task.B c) lrn.A and task.B and d)  lrn.B and task.A.
2) you can never merge 2 or 3 way combinations of those 4 BMR because a BMR object needs all cross-products of lrn.A and lrn.B with task.A and task.B. 
3) If you have more learners and tasks this can be much complicated and you can simply "forget" one combination.
4) The easiest way to check which combination is missing (so that the user can be notified a la `combining is not possible because you are missing task.X and lrn.X`) is to first group the BMR with a single learner and a single task by different learners (or tasks) and for each group trying to merge all remaining tasks (or learners) into one BMR...
Maybe I can explain it to you in real-life what was going on in my mind when I did this. But it maked sense to me to split this in two merging processes, I did not commit the global merger because it did not work for each special case.

**Comment by giuseppec** [comment]
@florianfendt here the global merge function that I have local (maybe it hepls). I did not a PR because its kind of experimental and currently works only for BMR with a single entry and should be extended to work with any BMR of any length. 

```r
#' @title Merge BenchmarkResults that contain only one benchmark experiment
#' 
#' @description Combines \code{\link{BenchmarkResult}} objects
#'   
#' @param ... [\code{\link{BenchmarkResult}}] \cr 
#'   \code{BenchmarkResult} objects that should be merged
#' 
mergeBenchmarkResults = function(...) {
  set = list(...)
  for (i in 1:length(set)) assertClass(set[[i]], "BenchmarkResult")
  
  # get number of benchmark experiments of all passed BenchmarkResults
  n.exp = viapply(set, function(X) nrow(unique(as.data.frame(X)[, c("task.id", "learner.id")])))
  # get the index of BenchmarkResult objects that contain more than one experiment
  ind = which(n.exp!=1)
  if (length(ind)!=0) 
    stopf("The 'BenchmarkResult' object(s) passed at position %s must contain only one experiment", 
      collapse(ind))
  
  # get task and learner names from BenchmarkResult objects
  task.names = vcapply(set, function(X) names(X$results))
  learner.names = vcapply(set, function(X) names(X$learners))
  # all possible combos
  all.combos = expand.grid(unique(task.names), unique(learner.names))
  # all combos that are contained in the passed BenchmarkResult objects
  existing.combos = data.frame(task.names, learner.names)
  
  # get missing combos
  diff = setdiff(apply(all.combos, 1, collapse, " with learner "), 
    apply(existing.combos, 1, collapse, " with learner "))
  if (length(diff)!=0) 
    stopf("The following Task-Learner combination are missing: \n-%s\n",
      collapse(diff, "\n-"))
  
  # split BenchmarkResult objects by tasks and combine all learners that were computed on each tasks
  split.by.tasks = split(set, as.factor(task.names))
  merged.by.tasks = lapply(split.by.tasks, 
    function(X) Reduce(function(...) mergeBenchmarkResultLearner(...), X))
  # merge all experiments
  merged = Reduce(function(...) mergeBenchmarkResultTask(...), merged.by.tasks)
  return(merged)
}
```
