### ISSUE TITLE
memory usage reporting in mlr

### ISSUE THREAD

**Issue by philippstats** [mlr-org/mlr#828]
Currently mlr (especially the function `logFunDefault`) uses `mem = colSums(gc()[, c(2L, 6L)])` to report the memory used by R. 
According to `?pryr::mem_used` another method should be used:

> R breaks down memory usage into Vcells (memory used by vectors) and Ncells (memory used by everything else). However, neither this distinction nor the "gc trigger" and "max used" columns are typically important. What we're usually most interested in is the the first column: the total memory used.

`mem_used` is calculated this way: `show_bytes(sum(gc()[, 1] * c(node_size(), 8)))`
Source [here](http://adv-r.had.co.nz/memory.html) in section "Sources".

**Comment by berndbischl** [comment]
But if I compare the mlr code and what you posted from pryr, we compute EXACTLY the same thing? 

There are only 2 differences I see:
a) We use col 2, which is simply the mem in MB (different unit)
b) We also report "max used" which IS INDEED of interest, at least to me. Because it can show what happened deep down in some learner call (executed before the current point in time).

I dont see how suppressing the info in b) would improve the package?

Reopen if you disagree please

**Comment by philippstats** [comment]
You're right!
