### ISSUE TITLE
Q: In which order are wrappers processed? / What happens with multiple wrappers?

### ISSUE THREAD

**Issue by bkomboz** [mlr-org/mlr#924]
Let's assume we have the following multiple wrapped learner:
```r
lrn <- makeLearner("regr.gbm")
lrn <- makeDownsampleWrapper(lrn, dw.perc = 0.1)
lrn <- makeImputeWrapper(lrn, classes = list(numeric = imputeMedian(), 
  integer = imputeMedian(), factor = imputeMode())
lrn <- makeTuneWrapper(lrn, resampling = makeResampleDesc("Resample", iters = 3, 
  split = 0.75), measures = list(rmse), par.set = ...)
```

What exactly happens when this learner is put inside a call to `resample()`? I assume the following happens, but I am not sure if this is correct:

For each outer resampling iteration from 1 ... n:

i. The given training data is downsampled to 0.1.

ii. This downsampled data is split into train&test according to the inner resampling scheme of the tune wrapper.

For each inner resampling iteration from 1... 3:

1. The missing values on the train data are imputed.

2. The learner is fitted to the imputed training data with a certain parameter combination.

3. Missing values in the test data are imputed with the values from the training data.

4. The fitted learner is used to predict the target on the imputed test data.

5. The requested measures are computed.

iii. The best tuned model is used to predict on the full(?) test data

iv. The requested measures are computed.

Is this correct? Does the downsampling really only affect the training data in the outer resampling loop or where exactly does it take place? If yes, that means the tuning is then completely based only on the downsampled training data? But the outer evaluation is always on the full data set?

**Comment by jakob-r** [comment]
It happens vice versa. From the most outer wrapper to the inner wrapper.

1. The data will be split in 1 ... n from  `resample()`. Now we go in to the first of those splits and...
2. execute the tuning on the split we got. 
3. we split this data again into the _tuning.train_ and _tuning.test_ split (repeated 3 times in your example) and depending on the tuning setting for each tuning evaluation a new split will be generated or not (the latter is teh default -- which might be debatable if you want that)
4. _tuning.train_ will be imputed
5. imputed _tuning.test_ will be downsampled
6. trainer learns on downsampled imputed _tuning.test_
7. imputation is done on tuning.train according to how we did _tuning.train_
8. tuning measure will be evaluated on imputed _tuning.train_ (note: no downsampling here)
9. 4-8 will be repeated 3 times and we obtain an averaged tuning measure
10. Repeat 3 (or 4)-9 until tuning stops
11. Repeat 2 to 10 n times in total

I hope I didn't mix things up and you are clear now :wink: 
Actually this order is also the kind of way you want to go to get a reliable tuning result. But maybe you should switch downsampling and imputation.

**Comment by berndbischl** [comment]
IMHO @jakob-r explained this nicely. just some comments from my side, to make it simpler.

a) you dont have to think about what happens when you put that learner into "resample".
that always the same. the whole learner (pipeline) is trained on the training sets and it predicts the test sets. so just ask yourself what the learner does during a normal "train" (and "predict"). makes it simpler.

b) the TuningWrapper you could also disregard. it also always does the same, whether you apply it to a basic learner, or a "complex pipeline". 

c) so that leaves you with basiclearner --> downsample --> impute. 
@jakob-r already explained nicely that this imputes the data first, then downsamples it, then the basiclearner is trained. 

@schiffner: could we maybe add an example / explanation like this to the tutorial? do you want an issue? this questions comes up quite often.

will close this here, as IMHO this is answered

**Comment by bkomboz** [comment]
Thanks for your responses and the explanations!
