### ISSUE TITLE
xgboost predict error

### ISSUE THREAD

**Issue by dickoa** [mlr-org/mlr#935]
Hi,
It appears that in the newer version of xgboost `predict` is not exported any more from the package namespace, therefore all code with `xgboost::predict` throw errors.

```{r}
library(xgboost)
library(mlr) 
packageVersion("mlr")
## [1] ‘2.9’

packageVersion("xgboost")
## [1] ‘0.4.3’

data(iris)
task <- makeClassifTask(id = "bug", data = iris, target = "Species")
classif.lrn <- makeLearner("classif.xgboost", predict.type = "prob")
rdesc <- makeResampleDesc(method = "CV", stratify = TRUE)
r <- resample(learner = classif.lrn, task = task, resampling = rdesc, show.info = FALSE)
## [0]	train-merror:0.022222
## Error: 'predict' is not an exported object from 'namespace:xgboost'
## Timing stopped at: 0.013 0 0.013 
```

The fix is to simply use `predict` without the `xgboost::` prefix in [R/RLearner_regr_xgboost.R] (https://github.com/mlr-org/mlr/blob/master/R/RLearner_regr_xgboost.R#L65) and [R/Learner_classif_xgboost.R](https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_xgboost.R#L84)

Do you want me to send a PR ?

Cheers,

**Comment by jakob-r** [comment]
I don't get this error on my system with the same versions. Are you in a fresh session?

**Comment by dickoa** [comment]
I still have the same error even when I don't load `xgboost`
I also tried a fresh install of both packages without any success.

```{r}

drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
devtools::install_github("mlr-org/mlr")
library(mlr) 
data(iris)
task <- makeClassifTask(id = "bug", data = iris, target = "Species")
classif.lrn <- makeLearner("classif.xgboost", predict.type = "prob")
rdesc <- makeResampleDesc(method = "CV", stratify = TRUE)
r <- resample(learner = classif.lrn, task = task, resampling = rdesc, show.info = FALSE)
## [0]  train-merror:0.022222
## Error: 'predict' is not an exported object from 'namespace:xgboost'
## Timing stopped at: 0.013 0 0.013 

```

**Comment by dickoa** [comment]
Looking at the `xgboost` gh repos, it doesn't look like the `predict` function is exported

https://github.com/dmlc/xgboost/blob/master/R-package/NAMESPACE

In my fresh install, I also have:
```{r}
getNamespaceExports("xgboost")
##  [1] "xgb.save"             "setinfo"             
##  [3] "xgb.plot.tree"        "slice"               
##  [5] "xgb.plot.multi.trees" "xgb.model.dt.tree"   
##  [7] "xgb.dump"             "getinfo"             
##  [9] "xgb.cv"               "xgboost"             
## [11] "xgb.train"            "print.xgb.DMatrix"   
## [13] "xgb.plot.importance"  "xgb.plot.deepness"   
## [15] "xgb.create.features"  "xgb.load"            
## [17] "xgb.DMatrix.save"     "xgb.importance"      
## [19] "xgb.save.raw"         "xgb.DMatrix"

```
May be it will be better to solve it at the [xgboost side](https://github.com/dmlc/xgboost/commit/71f402ac16ea408321c41473609a1a537570f4f4) is there someone else with the same problem ?

**Comment by mllg** [comment]
xgboost switched from S4 to S3 for `predict` on GitHub and you probably do have the GitHub version installed. The xgboost developers should increase the version number of the devel version, this is quite misleading.

**Comment by dickoa** [comment]
@mllg You are right, thanks

**Comment by berndbischl** [comment]
so can we close this here? or do we have to adapt something?

**Comment by berndbischl** [comment]
on my system i can see no problems with the latest version of xgboost from CRAN. 
which, in cases like these, is the one we support. 

reopen, if problems occur or a changed xgboost hits cran.

**Comment by dickoa** [comment]
@berndbischl Thanks, I will reopen if it ever strike again on the xgboost CRAN version.
Thanks again for the support and this wonderful package.

**Comment by lelayf** [comment]
I think this is happening again. Just did a fresh reinstall of CRAN xgboost 0.6.0 and predict is not in the list of exports.

**Comment by ja-thomas** [comment]
CRAN version is still 0.4.4, which should work with mlr.

We will support 0.6 as soon as they update the CRAN version.

In the meantime (if you really need to use xgboost 0.6.0) you can use the mlr branch xgboost_latest

**Comment by lelayf** [comment]
@ja-thomas ha sorry yes i did not realize 0.6.0 was on dmlc drat rather than CRAN. I ended up adding an empty predict wrapper in xgboost source to have roxygen2 properly export it, then reinstall xgboost from that local modified source. It seems the mlr xgboost_latest branch is still prefixing predict so I would expect that branch to generate the same namespace error ? I will verify this assumption a bit later. https://github.com/mlr-org/mlr/blob/xgboost_latest/R/RLearner_classif_xgboost.R#L92

**Comment by khotilov** [comment]
@lelayf the S3 method `predict.xgb.Booster` is exported as `S3method(predict,xgb.Booster)` and is available through the `predict` generic (defined in `stats::predict`). Thus, instead of `xgboost::predict` mlr needs to simply call `predict`, just like it does in its wrappers for all the other models with S3 `predict`.

Also note that `predict.xgb.Booster` has gained a `reshape` flag (default is FALSE for compatibility) that could be used to obtain a matrix of predictions in settings with several prediction values per instance (e.g., multiclass). That might be used to simplify the logic within `predictLearner.classif.xgboost` a bit.
